// GENERATED BY tools/pathcheck-split.mjs — do not hand-merge; re-run the script.
//
// The pathcheck prelude: the static layer guards, the assertion helpers, and
// the counters every domain module shares. It is evaluated once, before any
// domain runs, exactly where it sat in the monolith.
//
// Adding assertions? Add or edit a file in this directory and list it in
// manifest.mjs. You should not need to touch this file or ../pathcheck.mjs.
//
// ---- carried over from the monolith's header ---------------------------
// pathcheck.mjs — HULLBREAKER pure-layer harness.
//
// Imports src/config.js and the src/pure/* modules directly (the game is now
// split into ES modules, so there is no pure block to regex out of the HTML),
// checks that the pure layer still references no three.js/DOM surface and
// imports nothing outside itself, then runs the assertion suite below with
// node. Exits non-zero on any failure.
//
// Run from the repo root:  node tools/pathcheck.mjs
//
// T-032: the durability policy — fault-streak decisions and the rule the
// player-facing failure text has to pass.
//
// T-009: the lattice pass is asserted through its own exports (namespace
// import so the appended section stays one self-contained block).
//
// The sim layer carries the same no-three.js/no-DOM guarantee as pure/ (see
// guardLayer('sim', ...) below), so it is Node-importable exactly like the
// bot-player harness relies on. A handful of collision-edge assertions drive
// the real sim loop directly below, instead of re-deriving its physics.
//
// The render-side palette module (T-010) is deliberately Node-safe — no
// three.js, DOM writes guarded — precisely so its token tables and pure
// resolvers can be asserted here. The legibility module (T-003) is the
// second of that kind: pure scale arithmetic over CONFIG.viewScales, so the
// readability contract it encodes is checkable without a browser. These two
// are the ONLY render modules this harness imports; everything else
// render-side stays browser-only.
// ------------------------------------------------------------------------

import { fileURLToPath as __toPath } from 'node:url';
import { dirname as __dirOf } from 'node:path';
import { readdirSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { CONFIG } from '../../src/config.js';

// In the monolith `import.meta.url` meant tools/pathcheck.mjs, and every path in
// the suite is derived from it (srcDir, the tools dir the playtest harness is
// read from, the child processes' file:// bases). It keeps meaning that here,
// which is why the modules can sit one directory deeper without moving a path.
export const ENTRY_URL = new URL('../pathcheck.mjs', import.meta.url).href;
export const ENTRY_FILE = __toPath(ENTRY_URL);
export const ENTRY_DIR = __dirOf(ENTRY_FILE);

/* ---------------------- layer guards (static) ------------------------ *
 * The pure layer must stay runnable with zero three.js/DOM surface and must
 * not reach into src/sim, src/render, or src/ui — that is what makes it
 * testable here. The sim layer carries the same no-renderer rule (it may use
 * src/pure, src/config.js and src/mode.js): it is what lets a Node bot
 * harness import and step the whole simulation with no browser. Comments are
 * stripped first, so prose may still name three.js or the DOM.          */
const here = dirname(fileURLToPath(ENTRY_URL));
const srcDir = join(here, '..', 'src');
const layerFiles = (name) =>
  readdirSync(join(srcDir, name)).filter((f) => f.endsWith('.js')).map((f) => join(srcDir, name, f));

const banned = /\b(THREE|document|window|renderer|scene|addEventListener|requestAnimationFrame|innerWidth|innerHeight|devicePixelRatio|performance)\b/;
const stripComments = (src) =>
  src.replace(/\/\*[\s\S]*?\*\//g, ' ').replace(/^\s*\/\/.*$/gm, ' ').replace(/\/\/[^\n'"`]*$/gm, ' ');

function guardLayer(label, files, allowed) {
  for (const file of files) {
    const src = readFileSync(file, 'utf8');
    const hit = stripComments(src).match(banned);
    if (hit) {
      console.error('pathcheck: forbidden ' + label + ' reference in ' + file + ': ' + hit[0]);
      process.exit(1);
    }
    for (const m of src.matchAll(/^\s*(?:import|export)[^'"]*from\s*['"]([^'"]+)['"]/gm)) {
      if (!allowed(m[1])) {
        console.error('pathcheck: ' + label + ' module ' + file + ' imports across its layer: ' + m[1]);
        process.exit(1);
      }
    }
  }
}

guardLayer(
  'pure',
  [join(srcDir, 'config.js'), ...layerFiles('pure')],
  (spec) => spec === '../config.js' || /^\.\/[\w-]+\.js$/.test(spec),
);
guardLayer(
  'sim',
  layerFiles('sim'),
  (spec) => spec === '../config.js' || spec === '../mode.js' ||
    /^\.\/[\w-]+\.js$/.test(spec) || /^\.\.\/pure\/[\w-]+\.js$/.test(spec),
);

/* ===================== pathcheck test suite ====================== */
let fails = 0, passes = 0;
function ok(cond, msg) {
  if (cond) passes++;
  else { fails++; console.error('FAIL ' + msg); }
}
function near(a, b, eps, msg) {
  ok(Math.abs(a - b) <= eps, msg + ' [got ' + a + ', want ' + b + ']');
}
function fingerprint(value) {
  const text = JSON.stringify(value);
  let hash = 2166136261;
  for (let i = 0; i < text.length; i++) {
    hash ^= text.charCodeAt(i);
    hash = Math.imul(hash, 16777619);
  }
  return (hash >>> 0).toString(16).padStart(8, '0');
}

const PP = CONFIG.path, WW = CONFIG.waves;

/** Live tally, for the runner's one-line summary. */
export function counts() { return { passes, fails }; }

export {
  PP,
  WW,
  fingerprint,
  here,
  layerFiles,
  near,
  ok,
  srcDir,
  stripComments,
};
