// GENERATED BY tools/pathcheck-split.mjs
//
// The ordered domain manifest. ORDER IS SIGNIFICANT and this list is explicit
// on purpose: sections build values (levels, fixtures, probe results) that
// later sections read, and some drive the sim's module-level singletons and
// leave them set. Directory enumeration order is not stable across machines,
// so the runner never globs — it walks this list.
//
// Adding a domain: create the file, then add it here in the position it must
// run. Appending at the end is right for a new, self-contained section.

import * as d00 from './pathcheck-suite.mjs';
import * as d01 from './view-scale-experiment.mjs';
import * as d02 from './world-transitions.mjs';
import * as d03 from './g2-neck-access-plate-flip-gate.mjs';
import * as d04 from './pacing-variants.mjs';
import * as d05 from './movement-verb-prototypes.mjs';
import * as d06 from './authored-slope-rib-run.mjs';
import * as d07 from './rib-run-driven-through-real-sim.mjs';
import * as d08 from './headroom-over-every-authored-ground-run.mjs';
import * as d09 from './pursuit-model.mjs';
import * as d10 from './hull-fallback-tier-1.mjs';
import * as d11 from './charge-threat-prototype.mjs';
import * as d12 from './cp4-promotion-full-run-tune.mjs';
import * as d13 from './score-wiring-sim-layer.mjs';
import * as d14 from './cp4-promotion-wiring-default-run-score.mjs';
import * as d15 from './snap-hook-driven-through-real-sim.mjs';
import * as d16 from './damage-plane-never-leaves-geometry-behind.mjs';
import * as d17 from './hull-fallback-cannot-pay-itself.mjs';
import * as d18 from './g1-limb-read-tower-bend-cull.mjs';
import * as d19 from './bend-cull-driven-through-real-bullet.mjs';
import * as d20 from './g1-1-render-only-proved-sim.mjs';
import * as d21 from './t-002-ritual-decision-trace-frame.mjs';
import * as d22 from './t-003-far-view-legibility-compensation.mjs';
import * as d23 from './t-012-audio-layer-static-guards.mjs';
import * as d24 from './t-014-spore-mortar.mjs';
import * as d25 from './t-011-juice-feedback-pass.mjs';
import * as d26 from './t-013-game-shell.mjs';
import * as d27 from './t-009-six-face-lattice.mjs';
import * as d28 from './t-009-static-anatomy-reveal-default.mjs';
import * as d29 from './t-009-houndframe-stations-six-face.mjs';
import * as d30 from './t-009-non-gating-station-cannot.mjs';
import * as d31 from './t-009-whole-run-crossable-driven.mjs';
import * as d32 from './t-009-pocket-route-works-driven.mjs';
import * as d33 from './t-018-bot-harness-relative-geometry.mjs';
import * as d34 from './t-027-bot-harness-deterministic-dispatch.mjs';
import * as d35 from './t-025-harness-may-not-report.mjs';
import * as d36 from './momentum-earned-pace-escalation.mjs';
import * as d37 from './t-029-runtime-truth-three-debug.mjs';
import * as d38 from './pathcheck-suite-2.mjs';
import * as d39 from './t-041-impact-language.mjs';
import * as d40 from './t-043-wasp-aim-lock-squad.mjs';
import * as d41 from './t-039-contact-shadows.mjs';
import * as d42 from './pathcheck-suite-3.mjs';
import * as d43 from './t-035-value-ladder.mjs';
import * as d44 from './t-038-seam-pips.mjs';
import * as d45 from './t-047-light-rig.mjs';

export const DOMAINS = [
  d00,    // pathcheck suite
  d01,    // view-scale experiment (viewscale lane) ===========
  d02,    // world transitions (slice) ======================
  d03,    // G2 — neck access-plate flip gate (?g2=1) ==============
  d04,    // pacing variants (CP1) ==========================
  d05,    // MOVEMENT VERB PROTOTYPES (wave 3, opt-in) =============
  d06,    // THE AUTHORED SLOPE — rib run (?ribrun=1) ==============
  d07,    // the rib run, driven through the REAL sim loop ----------------
  d08,    // headroom over every authored ground run ---------------
  d09,    // pursuit model (pure step math) ------------------
  d10,    // HULL FALLBACK tier 1 (proposal B.1) --------------
  d11,    // CHARGE / THREAT prototype (proposal A.4) =============
  d12,    // CP4 promotion: the full-run tune (T-016) ===============
  d13,    // score wiring at the sim layer (A.1 semantics) ---------
  d14,    // CP4 promotion wiring: the DEFAULT run, ?score=1&fallback=1 ----
  d15,    // the snap hook, driven through the REAL sim loop --------------
  d16,    // the damage plane never leaves geometry behind it ------------------
  d17,    // HULL FALLBACK cannot pay for itself (fixture contract) ------------
  d18,    // G1: the limb read of the tower, and the bend cull -----------------
  d19,    // the bend cull, driven through the REAL bullet loop ----------------
  d20,    // ?g1=1 is render-only, proved at the sim layer --------------------
  d21,    // T-002: ritual decision trace + frame-scoped input determinism ----
  d22,    // T-003: FAR-view legibility compensation (entry 7)
  d23,    // T-012: audio layer (ui) static guards =================
  d24,    // T-014: SPORE MORTAR (?mortar=)
  d25,    // T-011: juice — the feedback pass ====================
  d26,    // T-013: game shell (pure + guards) ===================
  d27,    // T-009: the six-face lattice (route density) ==============
  d28,    // T-009: the static-anatomy reveal is the DEFAULT corner ritual -----
  d29,    // T-009: houndframe stations on the six-face run (faces 2+) ------
  d30,    // T-009: a non-gating station cannot hold a wave gate shut ----------
  d31,    // T-009: the whole run is crossable, driven through the REAL sim ----
  d32,    // T-009: the pocket route works, driven through the REAL sim --------
  d33,    // T-018: the bot harness's relative-geometry grammar ==========
  d34,    // T-027: the bot harness's deterministic-dispatch honesty ====
  d35,    // T-025: the harness may not report what the run did not do ========
  d36,    // MOMENTUM — earned pace escalation (T-022) =================
  d37,    // T-029 — runtime truth: three debug/copy surfaces ==========
  d38,    // pathcheck suite
  d39,    // T-041 impact language (S10)
  d40,    // T-043: wasp aim-lock + squad stagger (enemy aggression)
  d41,    // T-039: contact shadows (S6) =====================
  d42,    // pathcheck suite
  d43,    // T-035 value ladder (S1 + S2) ======================
  d44,    // T-038: warm-white seam pips and route-lip highlights (S5) ========
  d45,    // T-047 light rig, shadows, tone mapping (decisions 18)
];
