// GENERATED BY tools/pathcheck-split.mjs — assertions moved verbatim from the pathcheck monolith.
//
// Domain: pathcheck suite
//
// Edit this file to add assertions in this domain. Order inside the file is
// preserved as written; order between files is manifest.mjs's business.

import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { CONFIG } from '../../src/config.js';
import {
  FAILSAFE, FAILSAFE_KEYS, FAILSAFE_KINDS, PLAIN, faultStep, freshFaultState,
  plainLanguageIssues,
} from '../../src/pure/failsafe.js';
import { here, ok, srcDir, stripComments } from './_context.mjs';

export const title = 'pathcheck suite';

export async function run(SHARED) {

/* ==================================================================== *
 *  T-032 — DURABILITY: the failure a 9-year-old is allowed to meet
 *
 *  The incident this section gates: one stale cached module failed to
 *  parse, src/main.js never executed, and the operator's own page was a
 *  black void with a single console line. Nothing a player could read, and
 *  no hint that reloading would help.
 *
 *  So the claims asserted here are, in order: the policy that decides
 *  whether a broken frame costs the run is arithmetic and cannot drift; the
 *  words on the panel are readable by a child and carry no engineering
 *  jargon; the code that shows that panel runs even when every module in
 *  the graph is dead; and the frame loop cannot end up painting a still
 *  picture at a live page. What a browser has to prove instead — that the
 *  panel LANDS on screen, and that the words that render are the words in
 *  the table — is ?selftest=1's job (src/main.js), and the abuse scenarios
 *  are tools/durability/abuse.mjs's.
 * ==================================================================== */
{
  const T32_HTML = readFileSync(join(here, '..', 'index.html'), 'utf8');
  const T32_MAIN_SRC = readFileSync(join(srcDir, 'main.js'), 'utf8');
  const T32_MAIN = stripComments(T32_MAIN_SRC);
  const T32_UI = stripComments(readFileSync(join(srcDir, 'ui', 'failsafe.js'), 'utf8'));

  // --- the fault policy is arithmetic, not vibes -------------------------
  {
    const P = FAILSAFE;
    const fresh = freshFaultState();
    ok(fresh.faults === 0 && fresh.recoveries === 0 && !fresh.halted,
       'T-032: a fresh session starts with no faults, no recoveries and no halt');
    ok(faultStep(fresh, 1000, P).action === 'ignore',
       'T-032: ONE bad frame is a blip — it never costs a run');

    // a hiccup every 5 s for two minutes: the streak window expires between
    // them, so nothing ever accumulates into a restart or a shutdown
    {
      let s = freshFaultState(), worst = 'ignore';
      for (let t = 0; t <= 120000; t += 5000) {
        const r = faultStep(s, t, P);
        s = r;
        if (r.action !== 'ignore') worst = r.action;
      }
      ok(worst === 'ignore' && !s.halted,
         'T-032: a fault every 5 s for two minutes never restarts and never halts — ' +
         'faults more than ' + P.streakWindowMs + ' ms apart are separate incidents');
    }

    // a burst inside a tenth of a second is still a blip: the escalation is
    // measured in SECONDS of continuous breakage, not in frames
    {
      let s = freshFaultState(), worst = 'ignore';
      for (let i = 0; i < 20; i++) {
        const r = faultStep(s, i * 5, P);
        s = r;
        if (r.action !== 'ignore') worst = r.action;
      }
      ok(worst === 'ignore',
         'T-032: 20 faults inside 100 ms do not restart the run — ' +
         'the trigger is ' + P.recoverAfterMs + ' ms of continuous failure');
    }

    // continuous breakage at 60 fps: restart, restart, then the panel — and
    // the whole escalation is over in under two seconds, which is how long a
    // child is asked to look at a broken picture before it explains itself
    {
      let s = freshFaultState();
      const events = [];
      for (let f = 0; f < 600 && !s.halted; f++) {
        const t = f * (1000 / 60);
        const r = faultStep(s, t, P);
        s = r;
        if (r.action !== 'ignore') events.push({ t, action: r.action, faults: f + 1 });
      }
      const recovers = events.filter((e) => e.action === 'recover');
      const stops = events.filter((e) => e.action === 'stop');
      ok(recovers.length === P.maxRecoveries && stops.length === 1 && s.halted,
         'T-032: a permanently throwing frame spends exactly ' + P.maxRecoveries +
         ' restarts and then stops legibly (got ' + recovers.length + ' restarts, ' +
         stops.length + ' stops)');
      ok(recovers.length > 0 && recovers[0].t >= P.recoverAfterMs &&
         recovers[0].faults >= P.minFaults,
         'T-032: the first self-repair waits for ' + P.recoverAfterMs + ' ms AND ' +
         P.minFaults + ' faults, got ' + (recovers[0] ? recovers[0].t.toFixed(0) : '?') +
         ' ms / ' + (recovers[0] ? recovers[0].faults : '?') + ' faults');
      ok(stops.length === 1 && stops[0].t <= 2000,
         'T-032: …and the panel is up within 2 s of the first broken frame, got ' +
         (stops[0] ? stops[0].t.toFixed(0) : '?') + ' ms');
    }

    // halting is sticky: nothing re-arms a run behind a panel that is up
    {
      let s = { faults: 0, firstMs: 0, lastMs: 0, recoveries: 9, halted: true };
      for (let i = 0; i < 5; i++) s = faultStep(s, 10000 + i * 5000, P);
      ok(s.halted && faultStep(s, 99999, P).action === 'stop',
         'T-032: once the game has stopped it stays stopped — no fault reopens it');
    }

    // a nonsense clock must not be a way to kill a run
    ok(faultStep(freshFaultState(), NaN, P).action === 'ignore',
       'T-032: a non-finite timestamp cannot trip the policy');
  }

  // --- the words on the panel ------------------------------------------
  {
    const m = /var HB_FAIL_TEXT = (\{[\s\S]*?\n\s*\});/.exec(T32_HTML);
    ok(!!m, 'T-032: index.html carries the failure text as a table pathcheck can read');
    let text = null;
    if (m) { try { text = JSON.parse(m[1]); } catch (e) { text = null; } }
    ok(!!text, 'T-032: …and that table is literal data, not code — it parses');
    if (text) {
      for (const kind of FAILSAFE_KINDS) {
        const entry = text[kind];
        ok(!!entry && entry.t && entry.b && entry.a,
           'T-032: the "' + kind + '" failure has a title, an explanation and a way back');
      }
      const gated = [];
      for (const kind of FAILSAFE_KINDS)
        if (text[kind]) gated.push(text[kind].t, text[kind].b, text[kind].a);
      gated.push(text.hint, text.tell, text.more);
      for (const line of gated) {
        const issues = plainLanguageIssues(line);
        ok(issues.length === 0,
           'T-032: player-facing line reads plainly — "' + line + '"' +
           (issues.length ? ' [' + issues.join(', ') + ']' : ''));
      }
      ok(/\bR\b/.test(text.hint) && /button/i.test(text.hint),
         'T-032: the panel names BOTH ways back in (a key and a button), got "' +
         text.hint + '"');
      ok(FAILSAFE_KINDS.every((k) => /not your fault|Wait a moment/i.test(text[k].b)),
         'T-032: every failure tells the player it is not their fault (or what to do ' +
         'instead) — the panel is a 9-year-old\'s only signal, and blame is not a signal');
    }
    // the rule can actually fail — a gate that passes everything gates nothing
    ok(plainLanguageIssues('An uncaught SyntaxError: undefined is not a function').length >= 2,
       'T-032: the plain-language rule rejects engineer-speak');
    ok(plainLanguageIssues('The game stopped. It is not your fault.').length === 0,
       'T-032: …and accepts the words a child can read');
    ok(PLAIN.maxWordLetters <= 12 && PLAIN.maxSentenceWords <= 16,
       'T-032: the readability bounds stay child-sized');
  }

  // --- the bootstrap survives every module being dead --------------------
  {
    const inline = /<script>([\s\S]*?)<\/script>/.exec(T32_HTML);
    ok(!!inline && /__HB_FAILSAFE/.test(inline[1]),
       'T-032: the failure handler is an INLINE classic script — the incident it ' +
       'exists for is a module graph that never ran');
    if (inline) {
      const code = inline[1];
      ok(!/^\s*import\s/m.test(code) && !/\brequire\(/.test(code),
         'T-032: …and it imports nothing, so nothing it depends on can fail with the game');
      let syntaxOk = true, syntaxErr = '';
      try { new Function(code); } catch (e) { syntaxOk = false; syntaxErr = e.message; }
      ok(syntaxOk, 'T-032: the inline handler itself parses (nothing else can report it) ' +
         (syntaxOk ? '' : '— ' + syntaxErr));
      ok(T32_HTML.indexOf(inline[0]) < T32_HTML.indexOf('src="src/main.js"'),
         'T-032: …and it is installed BEFORE the game module, so a failure to load ' +
         'that module is already covered');
      const w = /var WATCH = \{ bootMs: (\d+), stallMs: (\d+), tickMs: (\d+) \};/.exec(code);
      ok(!!w && Number(w[1]) === FAILSAFE.bootWatchdogMs &&
         Number(w[2]) === FAILSAFE.freezeStallMs && Number(w[3]) === FAILSAFE.freezeTickMs,
         'T-032: the inline watchdog numbers are the policy\'s (' +
         (w ? w.slice(1).join('/') : 'missing') + ' vs ' + FAILSAFE.bootWatchdogMs + '/' +
         FAILSAFE.freezeStallMs + '/' + FAILSAFE.freezeTickMs + ') — a copy that is ' +
         'gated is not a second source of truth');
      const k = /var KEYS = \[([^\]]*)\];/.exec(code);
      const keys = k ? k[1].split(',').map((s) => s.trim().replace(/^'|'$/g, '')) : [];
      ok(keys.join(',') === FAILSAFE_KEYS.join(','),
         'T-032: the keys that put a player back in the game match the policy, got ' +
         keys.join(','));
      ok(/addEventListener\('error', caught, true\)/.test(code) &&
         /addEventListener\('unhandledrejection', caught\)/.test(code),
         'T-032: it listens in the CAPTURE phase for errors (a module that never ' +
         'loaded fires at its element, not at the page) and for rejected work');
      ok(/setTimeout\(function \(\) \{ if \(!booted\) show\('slow'\)/.test(code),
         'T-032: a boot that never finishes is told to the player, not left as a void');
      ok(/visibilitychange/.test(code) && /slept/.test(code),
         'T-032: the freeze watchdog knows a backgrounded or suspended page from a ' +
         'stuck one — a hidden tab paints nothing BY DESIGN and must never panel');
      for (const id of ['fail', 'failTitle', 'failBody', 'failBtn', 'failHint',
                        'failTell', 'failMore', 'failDetail'])
        ok(T32_HTML.includes('id="' + id + '"'),
           'T-032: the panel markup carries #' + id + ', which the bootstrap writes into');
    }
    // the panel covers everything else on screen, including the title and
    // the pause overlay — a failure the shell is painted over is a void again
    const zOf = (sel) => {
      const at = T32_HTML.indexOf(sel + ' {');
      if (at < 0) return NaN;
      const rule = T32_HTML.slice(at, T32_HTML.indexOf('}', at));
      const z = /z-index:\s*(\d+)/.exec(rule);
      return z ? Number(z[1]) : NaN;
    };
    ok(zOf('#fail') > zOf('#shell') && zOf('#shell') > zOf('#overlay'),
       'T-032: the failure panel sits above the shell and the state overlay (' +
       zOf('#fail') + ' > ' + zOf('#shell') + ' > ' + zOf('#overlay') + ')');
    // every player-facing line is marked, and every marked line is inside the
    // panel: ?selftest=1 gates exactly this set against the readability rule
    const panelBlock = T32_HTML.slice(T32_HTML.indexOf('<div id="fail"'),
                                      T32_HTML.indexOf('<script type="module"'));
    const marked = (T32_HTML.match(/class="[^"]*fail-plain/g) || []).length;
    const markedInPanel = (panelBlock.match(/class="[^"]*fail-plain/g) || []).length;
    ok(marked >= 5 && marked === markedInPanel,
       'T-032: every .fail-plain line lives inside the panel (' + markedInPanel +
       ' of ' + marked + ')');
  }

  // --- the frame loop cannot leave a still picture at a live page --------
  {
    const fn = /function frame\(t\) \{[\s\S]*?\n\}/.exec(T32_MAIN);
    ok(!!fn, 'T-032: the frame loop is where the game either recovers or fails');
    if (fn) {
      const body = fn[0];
      ok(body.indexOf('if (failsafeHalted()) return;') >= 0 &&
         body.indexOf('if (failsafeHalted()) return;') <
           body.indexOf('requestAnimationFrame(frame);'),
         'T-032: the halt check is the FIRST thing the loop does — once the panel is ' +
         'up the simulation stops instead of grinding out frames nobody can see');
      ok(body.indexOf('requestAnimationFrame(frame);') < body.indexOf('update(dt)'),
         'T-032: the next frame is requested before any work, so a throw cannot end ' +
         'the loop by accident');
      ok(/failsafeBeat\(\);/.test(body),
         'T-032: the loop beats every frame — that counter is what the freeze ' +
         'watchdog reads');
      ok(/try \{\s*update\(dt\);\s*\} catch \(err\) \{\s*if \(reportFault\('update', err\) === 'stop'\) return;/
         .test(body),
         'T-032: a simulation fault is caught and handed to the policy');
      // T-048 changed the SPELLING of the draw, not this property: the frame's
      // one draw went from `renderer.render(scene, camera)` to `renderFrame()`
      // (src/render/post.js), which is the composer when it is up and that
      // exact renderer.render call when it is not. What this assertion is
      // about — the draw sits in its OWN try/catch, so a step that throws
      // still paints the frame it broke on — is unchanged and still gated
      // here. That the draw path cannot lose the picture is asserted in
      // tools/pathcheck/t-048-post-pass.mjs.
      ok(/try \{\s*renderFrame\(\);\s*updateHUD\(\);\s*\} catch \(err\) \{\s*reportFault\('render', err\);/
         .test(body),
         'T-032: the draw is caught SEPARATELY, so a broken step still paints the ' +
         'frame it broke on');
    }
    // the clamp that makes a backgrounded tab survivable, read from source
    const clamp = /Math\.min\(\s*(\d+(?:\.\d+)?)\s*,\s*t\s*-\s*last\s*\)/.exec(T32_MAIN);
    ok(!!clamp && Number(clamp[1]) === FAILSAFE.frameDtMaxMs,
       'T-032: the frame loop clamps dt at the policy\'s ' + FAILSAFE.frameDtMaxMs +
       ' ms (got ' + (clamp ? clamp[1] : 'no clamp') + ') — Chrome suspends rAF in a ' +
       'hidden tab, and the frame that lands on return carries a minute of wall clock');
    ok(FAILSAFE.frameDtMaxMs / 1000 * CONFIG.player.runSpeed < 1,
       'T-032: …and one clamped frame still cannot cross a whole tile, so returning ' +
       'from a backgrounded tab cannot teleport RIG through a wall');
    ok(/installFailsafe\(\{ restart: \(\) => resetGame\(\) \}\);/.test(T32_MAIN),
       'T-032: the one repair the game can make on its own is a full resetGame');
    ok(/renderer\.domElement\.addEventListener\('webglcontextlost'/.test(T32_MAIN) &&
       /reportContextLost\(\)/.test(T32_MAIN),
       'T-032: a lost drawing surface — nothing thrown, loop still beating — fails ' +
       'legibly instead of leaving a still canvas');
    ok(/failsafe: failsafeSnapshot,/.test(T32_MAIN),
       'T-032: window.HB publishes the failsafe state a headless abuse run reads');
    ok(T32_MAIN.trim().endsWith('failsafeBooted();'),
       'T-032: boot is signalled by the LAST statement in main.js — until it runs, ' +
       'any failure is "the game could not start"');
    ok(/failure panel renders, offers a way back, and reads plainly/.test(T32_MAIN),
       'T-032: ?selftest=1 paints the real panel and gates the words that RENDERED');
  }

  // --- one policy governs every fault -----------------------------------
  {
    ok(/from '\.\.\/pure\/failsafe\.js'/.test(T32_UI),
       'T-032: the view layer takes its decisions from the pure policy');
    ok(/api\.onUncaught = /.test(T32_UI) && (T32_UI.match(/faultStep\(/g) || []).length >= 2,
       'T-032: uncaught errors AND broken frames run through the same fault streak — ' +
       'one policy, so a storm of either is treated the same way');
    ok(/export function failsafeHalted\(\)/.test(T32_UI) &&
       /export function failsafeSelfCheck\(\)/.test(T32_UI),
       'T-032: the halt flag and the browser self-check are exported for main.js');
  }
}
}
