// GENERATED BY tools/pathcheck-split.mjs — assertions moved verbatim from the pathcheck monolith.
//
// Domain: pathcheck suite
//
// Edit this file to add assertions in this domain. Order inside the file is
// preserved as written; order between files is manifest.mjs's business.

import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { CONFIG } from '../../src/config.js';
import { CORNER_S } from '../../src/pure/path.js';
import { buildLevel } from '../../src/pure/generator.js';
import {
  limbAbovePlayBand, limbBackdropGaps, limbBackdropPieces, limbBakePlan, limbFogFactor,
  limbOutwardReach,
} from '../../src/pure/limb.js';
import { near, ok, srcDir, stripComments } from './_context.mjs';

export const title = 'pathcheck suite';

export async function run(SHARED) {
  const { B, gH } = SHARED;   // built by earlier domains

/* ==================================================================== *
 * T-045 — THE SCALE PASS: graded backdrop tiers + human-scale marks
 *
 * decisions.md entry 17 makes selling the scale of the Meridian the art
 * problem, with FAR frozen and RIG small on purpose. This block asserts the
 * four claims that pass makes, and every one of them is about what a PLAYER
 * can compare, not about what the author intended:
 *
 *   1. distance GRADES — the tiers land on a haze ladder inside the shipped
 *      band, at the same factors at every ?view=;
 *   2. nothing new is drawn in the air the fight happens in;
 *   3. something enormous is in frame at every point of the run;
 *   4. a known-size object exists on BOTH the near limb and the far one, at
 *      the same absolute size, measured against RIG's own body height.
 *
 * Self-contained by construction (one block, its own bindings) so it lifts
 * into a tools/pathcheck/ domain module verbatim once T-037's split lands.  */
{
  const L = CONFIG.limb;
  const B = L.backdrop;
  const level = buildLevel(CONFIG);
  const gH = level.groundH;
  const plan = limbBakePlan(CONFIG, gH);
  const legacy = limbBakePlan(CONFIG, gH, { scale: false });
  const back = limbBackdropPieces(plan, CONFIG);
  const tiers = [B.sister, B.spine, B.far];

  // --- 1. the haze ladder ----------------------------------------------
  {
    const f = tiers.map((t) => limbFogFactor(t.depth, CONFIG));
    for (let i = 0; i < f.length; i++)
      ok(f[i] >= 0.25 && f[i] <= 0.85,
         'backdrop tier ' + i + ' (depth ' + tiers[i].depth + ') grades at f=' +
         f[i].toFixed(3) + ', inside the visible haze band [0.25, 0.85]');
    for (let i = 1; i < f.length; i++)
      ok(f[i] - f[i - 1] >= 0.15,
         'tier ' + i + ' is a SEPARATE step, not the same field: f ' +
         f[i - 1].toFixed(3) + ' -> ' + f[i].toFixed(3) + ' (delta ' +
         (f[i] - f[i - 1]).toFixed(3) + ', floor 0.15)');
    // ?view= shifts the band by exactly the pull-back (src/render/camera.js's
    // calibrateEdges), so a tier authored once must grade identically at all
    // three. Computed the long way here — through the shift — rather than
    // trusting the cancellation the helper relies on.
    for (const v of Object.values(CONFIG.viewScales)) {
      const camZ = CONFIG.camera.z * v.depthMult;
      const near = L.fog.near + camZ - CONFIG.camera.z;
      const far = L.fog.far + camZ - CONFIG.camera.z;
      for (let i = 0; i < tiers.length; i++) {
        const shifted = (camZ + Math.abs(tiers[i].depth) - near) / (far - near);
        ok(Math.abs(shifted - f[i]) < 1e-9,
           'tier ' + i + ' grades the same at ?view=' + v.id + ' (' +
           shifted.toFixed(4) + ' vs ' + f[i].toFixed(4) + ')');
      }
    }
    // every piece, not just the authored tier depth
    const outOfBand = back.filter((p) => {
      const g = limbFogFactor(p.depth, CONFIG);
      return !(g >= 0.25 && g <= 0.85);
    });
    ok(outOfBand.length === 0,
       'every one of the ' + back.length + ' backdrop pieces is inside the haze ' +
       'band' + (outOfBand.length ? ': ' + outOfBand[0].kind + ' at depth ' +
       outOfBand[0].depth + ' grades ' + limbFogFactor(outOfBand[0].depth, CONFIG).toFixed(2) : ''));
    // …and the thing this replaced did NOT: the ?scale=0 slab at depth -34
    // computes f = 1.16, i.e. it is drawn in exactly the background color.
    // Asserted so the defect stays documented rather than remembered.
    const invisible = limbBackdropPieces(legacy, CONFIG)
      .filter((p) => limbFogFactor(p.depth, CONFIG) >= 1);
    ok(invisible.length > 0,
       'the ?scale=0 backdrop still contains the fully-hazed slab this pass ' +
       'replaced (f=' + limbFogFactor(invisible[0].depth, CONFIG).toFixed(2) +
       ' at depth ' + invisible[0].depth + '): that is the A/B, not a regression');
  }

  // --- 2. the play-band fence, at every shipped view --------------------
  {
    for (const v of Object.values(CONFIG.viewScales)) {
      const bad = back.filter((p) => !limbAbovePlayBand(p, CONFIG, v.depthMult));
      const floor = CONFIG.camera.y + (L.playBand.y1 - CONFIG.camera.y) *
        (CONFIG.camera.z * v.depthMult + Math.abs(B.far.depth)) /
        (CONFIG.camera.z * v.depthMult);
      ok(bad.length === 0,
         'at ?view=' + v.id + ' every backdrop piece draws entirely ABOVE the ' +
         'play band (deepest tier floor y=' + floor.toFixed(2) + ')' +
         (bad.length ? ': ' + bad[0].kind + ' bottoms at y=' +
          (bad[0].y - bad[0].h / 2).toFixed(2) + ' at depth ' + bad[0].depth : ''));
    }
    // the same claim stated as the consequence that matters: a hostile at the
    // top of its lane can never be drawn against new backdrop mass
    ok(L.playBand.y1 >= CONFIG.gen.laneCapY + 0.5,
       'the fence is drawn at the protected band, which clears the hostile ' +
       'lane cap (' + L.playBand.y1 + ' vs ' + CONFIG.gen.laneCapY + ')');
    // and nothing in the pass is outward mass the fall rules have to judge
    const marks = plan.filter((p) => p.kind.startsWith('mark'));
    ok(marks.length > 0 && marks.every((p) => limbOutwardReach(p, CONFIG) <= 0),
       'not one of the ' + marks.length + ' reference objects reaches past the ' +
       'combat plane: they can never hide RIG, a hostile, a bullet or a fall');
    ok(plan.filter((p) => limbOutwardReach(p, CONFIG) > L.fallOutwardMax).length ===
       CORNER_S.length * 2,
       'the pass adds no far-outward mass: still exactly the joint buttress and cup');
  }

  // --- 3. something enormous is always in frame -------------------------
  {
    // Conservative on purpose: the real half-window at the shipped FAR view is
    // tan(fov/2) * (camera.z*1.9 + 24) * aspect ~ 63 tiles at 16:9, so
    // requiring far-body mass within one chamfer of the camera's own column is
    // a far stronger test than "in frame" needs.
    const gaps = limbBackdropGaps(plan, CONFIG, CONFIG.path.chamferTiles);
    ok(gaps.length === 0,
       'the far body overlaps every column of the run' +
       (gaps.length ? ': no mass within ' + CONFIG.path.chamferTiles +
        ' tiles of s in [' + gaps[0][0] + ', ' + gaps[0][1] + ']' : ''));
    // it also has to be big: a mass under a few tiles tall is a smudge, not a body
    const mass = plan.filter((p) => p.kind === 'bdFar');
    ok(mass.every((p) => p.h >= 5) && mass.length >= CONFIG.path.faces,
       'every far-body segment is at least 5 tiles tall and there is at least ' +
       'one per face (' + mass.length + ' segments, shortest ' +
       Math.min(...mass.map((p) => p.h)).toFixed(1) + ')');
    // the contrast that makes the claim worth asserting: the build this
    // replaced has NO far-body mass at all, so its gap is the whole level
    const wasGap = limbBackdropGaps(legacy, CONFIG, CONFIG.path.chamferTiles);
    ok(wasGap.length === 1 && wasGap[0][0] === 0 &&
       wasGap[0][1] >= CONFIG.levelLength - 0.5,
       '?scale=0 has no far-body mass anywhere in the run (gap ' +
       JSON.stringify(wasGap) + '): the coverage claim above is a difference, ' +
       'not a restatement');
  }

  // --- 4. the comparison object, on both limbs, at one size -------------
  {
    const marks = plan.filter((p) => p.kind.startsWith('mark'));
    const near = marks.filter((p) => p.depth > 0);
    const farSide = marks.filter((p) => p.depth < 0);
    ok(near.length > 0 && farSide.length > 0,
       'reference objects exist on BOTH the limb RIG runs on (' + near.length +
       ') and the backdrop limb behind it (' + farSide.length + ') — a scale ' +
       'cue with only one end is not a comparison');
    const dims = (list, kind) => [...new Set(list.filter((p) => p.kind === kind)
      .map((p) => p.w.toFixed(3) + 'x' + p.h.toFixed(3)))];
    for (const kind of ['markRung', 'markStile']) {
      const a = dims(near, kind), b = dims(farSide, kind);
      ok(a.length > 0 && b.length > 0 && a.every((d) => d.split('x')[0] === b[0].split('x')[0]),
         kind + ' is the SAME absolute width on both limbs (' + a.join(',') +
         ' vs ' + b.join(',') + '): an object re-sized to look good at distance ' +
         'is not a reference object');
    }
    // …and the size is a person's, traced to the sim's own body constant
    const RIG = CONFIG.player.height;
    const door = L.mark.door, rung = L.mark.ladder;
    ok(door.rimH >= RIG * 1.2 && door.rimH <= RIG * 2.0,
       'a door is door-sized against RIG himself: ' + door.rimH + ' tiles vs a ' +
       RIG + '-tile marine (' + (door.rimH / RIG).toFixed(2) + 'x)');
    ok(rung.pitch <= RIG / 2 && rung.rungW >= CONFIG.player.width,
       'a ladder is climbable by that same marine: rungs ' + rung.pitch +
       ' apart (<= half his height) and ' + rung.rungW + ' wide (>= his ' +
       CONFIG.player.width + '-tile shoulders)');
    ok(L.mark.rail.postH <= RIG * 0.8,
       'a gantry rail is waist-high on him, not a wall (' + L.mark.rail.postH + ')');
    // they are where a player looks, not off-screen: the near marks all sit
    // below the play band and inside the frame at the shipped FAR view
    const camZ = CONFIG.camera.z * CONFIG.viewScales.far.depthMult;
    const halfT = Math.tan(CONFIG.camera.fov / 2 * Math.PI / 180);
    const bottomOfFrame = (d) => {
      const D = camZ + Math.abs(d);
      return CONFIG.camera.y - (CONFIG.camera.y - CONFIG.camera.lookY) * (D / camZ) - halfT * D;
    };
    ok(near.every((p) => p.y + p.h / 2 <= L.playBand.y0),
       'every near-limb reference object sits below the protected play band: ' +
       'detail under the deck cannot compete with a hostile');
    ok(near.every((p) => p.y - p.h / 2 >= bottomOfFrame(p.depth)),
       'every near-limb reference object is inside the frame at FAR (bottom of ' +
       'frame y=' + bottomOfFrame(0.66).toFixed(1) + '): a cue that is off-screen ' +
       'is not a cue');
    ok(near.every((p) => p.y + p.h / 2 <= L.mark.band.y0 + 1e-9 &&
                         p.y - p.h / 2 >= L.mark.band.y1 - 1e-9),
       'every near-limb reference object is inside the authored hull-skirt band [' +
       L.mark.band.y1 + ', ' + L.mark.band.y0 + ']');
  }

  // --- the pass costs no draw call, and the escape hatch is honest ------
  {
    const rsrc = readFileSync(join(srcDir, 'render', 'limb.js'), 'utf8');
    const table = rsrc.slice(rsrc.indexOf('const MATERIAL_FOR = {'),
                             rsrc.indexOf('};', rsrc.indexOf('const MATERIAL_FOR = {')));
    const map = new Map();
    for (const m of table.matchAll(/(\w+):\s*'(\w+)'/g)) map.set(m[1], m[2]);
    const kinds = [...new Set(plan.map((p) => p.kind))];
    const unmapped = kinds.filter((k) => !map.has(k));
    ok(unmapped.length === 0,
       'every kind the bake emits has a material (' + kinds.length + ' kinds)' +
       (unmapped.length ? ': ' + unmapped.join(', ') + ' would fall back to hull' : ''));
    // ONE instanced draw per distinct material: the count of distinct
    // materials IS the limb's draw-call count, and the scale pass may not
    // raise it. The budget for this pass was +1 to +2; it spends 0.
    const usedNow = new Set(kinds.map((k) => map.get(k)));
    const usedLegacy = new Set([...new Set(legacy.map((p) => p.kind))].map((k) => map.get(k)));
    ok(usedNow.size === usedLegacy.size,
       'the scale pass adds no material bucket, therefore no draw call: ' +
       usedNow.size + ' instanced draws with it, ' + usedLegacy.size + ' without');
    ok(/QUERY\.get\('scale'\) !== '0'/.test(rsrc),
       'the pass is ON by default with ?scale=0 as the escape hatch (entry 16)');
    const bdKinds = kinds.filter((k) => k.startsWith('bd') || k.startsWith('mark'));
    ok(bdKinds.length >= 8 &&
       legacy.every((p) => !p.kind.startsWith('bd') && !p.kind.startsWith('mark')),
       '?scale=0 emits none of the ' + bdKinds.length + ' new kinds: it is the ' +
       'build the operator has been looking at, not a half-off variant');
    ok(legacy.filter((p) => p.kind === 'silhouette').length ===
       (CONFIG.path.faces + 1) * L.silhouette.length,
       '?scale=0 restores exactly the old silhouette pair, one set per facet');
    // static anatomy: the new emitters take no time and roll no dice
    const psrc = stripComments(readFileSync(join(srcDir, 'pure', 'limb.js'), 'utf8'));
    ok(!/Math\.random|\bgameMs\b|\bperformance\b/.test(psrc),
       'the scale pass is a bake like everything else in the limb: no clock, no rng');
    ok(JSON.stringify(plan) === JSON.stringify(limbBakePlan(CONFIG, gH)) &&
       JSON.stringify(legacy) === JSON.stringify(limbBakePlan(CONFIG, gH, { scale: false })),
       'both plans are deterministic: same config, same body, every run');
  }
}
}
