// GENERATED BY tools/pathcheck-split.mjs — assertions moved verbatim from the pathcheck monolith.
//
// Domain: pathcheck suite
//
// Edit this file to add assertions in this domain. Order inside the file is
// preserved as written; order between files is manifest.mjs's business.

import { execFileSync } from 'node:child_process';
import { join } from 'node:path';
import { CONFIG } from '../../src/config.js';
import {
  DEG, CORNER_S, SEGS, HALT_S, polyAt, headingAt, yawAt, faceIndexAt,
} from '../../src/pure/path.js';
import {
  waveSize, waveLane, easeOutBack, cornerTimeline, cornerEventTotalMs, cornerYawDeltaDeg,
  cornerScrollVel, zipperOffset,
} from '../../src/pure/waves.js';
import {
  TRAVERSAL_FIXTURE, traversalSolidAllowsGrab, traversalFollowTarget,
  traversalCameraDepth,
} from '../../src/pure/traversal.js';
import {
  solidRectContains, levelSolidCell, buildLevel, buildTraversalLevel, GAP,
} from '../../src/pure/generator.js';
import { VERTICAL_ASSAULT } from '../../src/pure/vertical-assault.js';
import { PP, WW, fingerprint, near, ok, srcDir } from './_context.mjs';

export const title = 'pathcheck suite';

export async function run(SHARED) {

// --- level arithmetic --------------------------------------------------
ok(CONFIG.levelLength === PP.introTiles + PP.faces * PP.faceTiles + PP.outroTiles,
   'levelLength = intro + faces*faceTiles + outro');
ok(CORNER_S.join(',') === '89,154,219,284,349,414',
   'cornerS list, got ' + CORNER_S.join(','));
ok(HALT_S.join(',') === '75,140,205,270,335,400',
   'haltS = cornerS - haltOffset, got ' + HALT_S.join(','));

// --- segment table / circuit closure ----------------------------------
ok(SEGS.length === 1 + 2 * PP.faces, '2 bends per corner -> 13 segments, got ' + SEGS.length);
ok(SEGS[0].s0 === 0 && SEGS[0].x === 0 && SEGS[0].z === 0 && SEGS[0].heading === 0,
   'path starts at origin, heading 0');
near(SEGS[SEGS.length - 1].heading, 2 * Math.PI * PP.turnSign, 1e-9,
     'headings complete a 360 deg circuit');

// bend anchors agree with polyAt
for (let i = 1; i < SEGS.length; i++) {
  const p = polyAt(SEGS, SEGS[i].s0);
  near(p.x, SEGS[i].x, 1e-9, 'anchor x at segment ' + i);
  near(p.z, SEGS[i].z, 1e-9, 'anchor z at segment ' + i);
}
// continuity across every bend
for (let i = 1; i < SEGS.length; i++) {
  const a = polyAt(SEGS, SEGS[i].s0 - 1e-7);
  const c = polyAt(SEGS, SEGS[i].s0 + 1e-7);
  ok(Math.hypot(a.x - c.x, a.z - c.z) < 1e-5, 'polyAt continuous at bend ' + i);
}
// arc length: unit steps stay unit inside faces, and never stretch anywhere;
// a step straddling one 30 deg bend may shrink to at most cos(15 deg).
{
  const a = polyAt(SEGS, 40), c = polyAt(SEGS, 41);
  near(Math.hypot(a.x - c.x, a.z - c.z), 1, 1e-9, 'unit spacing inside a face');
}
{
  let bad = 0;
  const lo = Math.cos(PP.turnDeg * DEG / 2) - 1e-6;
  for (let s = 0; s < CONFIG.levelLength; s++) {
    const a = polyAt(SEGS, s), c = polyAt(SEGS, s + 1);
    const d = Math.hypot(a.x - c.x, a.z - c.z);
    if (d > 1 + 1e-9 || d < lo) { bad++; console.error('  bad step at s=' + s + ' d=' + d); }
  }
  ok(bad === 0, 'every unit step length in [cos(15deg), 1]');
}

// --- headings (sharp) --------------------------------------------------
near(headingAt(SEGS, 50), 0, 0, 'face 1 heading 0');
near(headingAt(SEGS, 89.5), 30 * DEG, 1e-12, 'chamfer diagonal heading 30 deg');
near(headingAt(SEGS, 91.5), 60 * DEG, 1e-12, 'face 2 heading 60 deg');
near(headingAt(SEGS, 300), 240 * DEG, 1e-9, 'after 4 corners heading 240 deg');
near(headingAt(SEGS, 440), 360 * DEG, 1e-9, 'outro heading 360 deg');

// --- yaw blending (dynamic entities) ----------------------------------
near(yawAt(SEGS, 88, 1), 0, 1e-12, 'yaw untouched 1 tile before first bend');
near(yawAt(SEGS, 90, 1), 30 * DEG, 1e-9, 'yaw exactly mid-corner at chamfer center');
near(yawAt(SEGS, 92, 1), 60 * DEG, 1e-9, 'yaw complete 1 tile after second bend');
near(yawAt(SEGS, 120, 1), 60 * DEG, 1e-9, 'yaw equals face heading mid-face');
near(yawAt(SEGS, 50, 0), headingAt(SEGS, 50), 0, 'blend 0 degrades to sharp heading');
{
  let prev = -1, mono = true;
  for (let s = 87; s <= 93; s += 0.05) {
    const y = yawAt(SEGS, s, PP.yawBlendTiles);
    if (y < prev - 1e-9) mono = false;
    prev = y;
  }
  ok(mono, 'yaw monotone through a corner');
}

// --- face indexing -----------------------------------------------------
ok(faceIndexAt(0, CONFIG) === 0 && faceIndexAt(23, CONFIG) === 0, 'intro is face 0');
ok(faceIndexAt(24, CONFIG) === 1 && faceIndexAt(88, CONFIG) === 1, 'face 1 spans 24..88');
ok(faceIndexAt(89, CONFIG) === 2, 'corner column belongs to the next face');
ok(faceIndexAt(413, CONFIG) === 6, 'last face column');
ok(faceIndexAt(414, CONFIG) === 7 && faceIndexAt(444, CONFIG) === 7, 'outro is face 7');

// --- corner ritual timeline -------------------------------------------
const total = cornerEventTotalMs(CONFIG);
ok(total === 1100, 'event total 1100 ms, got ' + total);
near(cornerYawDeltaDeg(0, CONFIG), 0, 1e-9, 'yawDelta 0 at t=0');
near(cornerYawDeltaDeg(-50, CONFIG), 0, 1e-9, 'yawDelta 0 before event');
near(cornerYawDeltaDeg(69.999, CONFIG), WW.windUpDeg, 0.01, 'wind-up reaches -1.5 deg');
near(cornerYawDeltaDeg(220, CONFIG), 30, 1e-9, 'snap 1 lands exactly 30 at impact frame');
near(cornerYawDeltaDeg(350, CONFIG), 30, 1e-9, 'ratchet hold flat at 30');
near(cornerYawDeltaDeg(770, CONFIG), 60, 1e-9, 'snap 2 lands exactly 60');
near(cornerYawDeltaDeg(1100, CONFIG), 60, 1e-9, 'settled at 60 at event end');
near(cornerYawDeltaDeg(99999, CONFIG), 60, 1e-9, 'clamped after event');
{
  let minY = 0;
  for (let t = 0; t <= 70; t += 0.25) minY = Math.min(minY, cornerYawDeltaDeg(t, CONFIG));
  near(minY, WW.windUpDeg, 0.05, 'wind-up dips to windUpDeg');
}
{
  let peak = 0;
  for (let t = 70; t <= 220; t += 0.25) peak = Math.max(peak, cornerYawDeltaDeg(t, CONFIG));
  ok(peak > 30.5 && peak < 32, 'snap 1: single small overshoot (~1.4 deg), peak ' + peak);
}
{
  let peak = 0;
  for (let t = 640; t <= 770; t += 0.25) peak = Math.max(peak, cornerYawDeltaDeg(t, CONFIG));
  ok(peak > 60.4 && peak < 62, 'snap 2: single small overshoot, peak ' + peak);
}
// hold intervals must be perfectly flat (clack ... clack, no wobble)
{
  let flat = true;
  for (let t = 220; t <= 640; t += 1) if (cornerYawDeltaDeg(t, CONFIG) !== 30) flat = false;
  for (let t = 770; t <= 1100; t += 1) if (cornerYawDeltaDeg(t, CONFIG) !== 60) flat = false;
  ok(flat, 'holds are dead flat');
}
// easeOutBack shape at s = backS
near(easeOutBack(0, WW.backS), 0, 1e-12, 'easeOutBack(0) = 0');
near(easeOutBack(1, WW.backS), 1, 1e-12, 'easeOutBack(1) = 1');
{
  let eMax = 0;
  for (let u = 0; u <= 1; u += 0.0005) eMax = Math.max(eMax, easeOutBack(u, WW.backS));
  ok(eMax > 1.02 && eMax < 1.06, 'easeOutBack overshoot ~5 percent, got ' + eMax);
}

// --- scroll resume -----------------------------------------------------
ok(cornerScrollVel(0, CONFIG) === 0 && cornerScrollVel(899.9, CONFIG) === 0,
   'scroll frozen until t=900');
near(cornerScrollVel(1000, CONFIG), CONFIG.scrollSpeed * 0.25, 1e-9,
     'quadratic ease at resume midpoint');
near(cornerScrollVel(1100, CONFIG), CONFIG.scrollSpeed, 1e-9, 'full speed at event end');
near(cornerScrollVel(5000, CONFIG), CONFIG.scrollSpeed, 1e-9, 'clamped to full speed after');

// --- brick zipper ------------------------------------------------------
ok(zipperOffset(219, 0, CONFIG).phase === 'hidden', 'column 0 hidden before impact frame');
near(zipperOffset(220, 0, CONFIG).dy, WW.zipDropTiles, 1e-9, 'column 0 starts 2.75 above');
near(zipperOffset(280, 0, CONFIG).dy, WW.zipDropTiles * 0.75, 1e-9,
     'gravity ease: u=0.5 -> 75 percent of drop remains');
ok(zipperOffset(235, 1, CONFIG).phase === 'hidden' && zipperOffset(236, 1, CONFIG).phase === 'drop',
   'column 1 starts exactly 16 ms later');
{
  const d = zipperOffset(220 + WW.zipDropMs + 1, 0, CONFIG);
  ok(d.phase === 'dip' && Math.abs(d.dy + WW.zipDipTiles) < 1e-9, 'one-beat dip after landing');
}
{
  const l = zipperOffset(220 + WW.zipDropMs + WW.zipDipMs + 1, 0, CONFIG);
  ok(l.phase === 'locked' && l.dy === 0, 'column locks to base after dip');
}
{
  const lastLand = WW.zipStartMs + (WW.zipCols - 1) * WW.zipPerColMs + WW.zipDropMs;
  ok(lastLand === 820 && lastLand < total,
     'last slam column lands at 820 ms, before the event ends (' + lastLand + ')');
  const T = cornerTimeline(CONFIG);
  ok(lastLand + WW.zipDipMs <= T.t5,
     'zipper fully locked (' + (lastLand + WW.zipDipMs) + ' ms) before scroll resumes (t5=' + T.t5 + ')');
}

// --- waves -------------------------------------------------------------
ok([1, 2, 3, 4, 5, 6].map(function (k) { return waveSize(k, CONFIG); }).join(',') === '4,5,6,7,8,9',
   'wave sizes 4..9');

// --- wave composition (escalation across the 6 faces) ------------------
{
  let prevMean = -1, okComp = true;
  for (let k = 1; k <= PP.faces; k++) {
    const comp = WW.comp[k - 1];
    if (comp.length !== waveSize(k, CONFIG)) { okComp = false; console.error('  comp length wave ' + k); }
    let sum = 0, hasLow = false;
    for (const c of comp) {
      if (!(c >= 0 && c < WW.laneHeights.length)) okComp = false;
      if (c === 0) hasLow = true;
      sum += c;
    }
    if (!hasLow) { okComp = false; console.error('  wave ' + k + ' has no low-lane slot'); }
    if (k >= 3 && comp.indexOf(2) < 0) { okComp = false; console.error('  wave ' + k + ' lacks a high slot'); }
    const mean = sum / comp.length;
    if (mean < prevMean - 1e-9) { okComp = false; console.error('  altitude mix regresses at wave ' + k); }
    prevMean = mean;
  }
  ok(okComp, 'wave comp: sizes match waveSize, lanes valid, altitude mix escalates');
}
ok(waveLane(1, 0, CONFIG) === WW.laneHeights[WW.comp[0][0]] &&
   waveLane(6, 8, CONFIG) === WW.laneHeights[WW.comp[5][8]] &&
   waveLane(2, 7, CONFIG) === WW.laneHeights[WW.comp[1][7 % 5]],
   'waveLane maps comp slots to lane heights (wrapping)');

// --- retune constants --------------------------------------------------
const PL = CONFIG.player, CC = CONFIG.camera, GG = CONFIG.gen, SP = CONFIG.spawner;
ok(CONFIG.scrollSpeed === 4.3 && PL.runSpeed === 9.4 && PL.accelGround === 120 && PL.accelAir === 76,
   'stage-2 motion retune (4.3 / 9.4 / 120 / 76)');
ok(PL.jumpVel === 14 && PL.gravity === -36 && PL.fallGravityMult === 1.5 && PL.terminalVel === -32 &&
   PL.jumpCutMult === 0.45 && PL.airJumps === 1 && PL.airJumpVel === 13,
   'jump tune frozen');
const apex1 = PL.jumpVel * PL.jumpVel / (2 * -PL.gravity);
const apex2 = PL.airJumpVel * PL.airJumpVel / (2 * -PL.gravity);
ok(apex1 > 2.2 && apex1 < 3, 'single jump clears +2 lanes, not +3 (apex ' + apex1 + ')');
ok(apex1 + apex2 > 3.4, 'double jump clears +3 lanes (apex ' + (apex1 + apex2) + ')');
{
  const tUp = PL.jumpVel / -PL.gravity;
  const tDown = Math.sqrt(2 * apex1 / (-PL.gravity * PL.fallGravityMult));
  ok((tUp + tDown) * PL.runSpeed > CONFIG.gen.gapMax + 1.5,
     'full jump at run speed clears the widest gap with margin');
}
ok(CC.fov === 56 && CC.x === 5.0 && CC.y === 6.2 && CC.z === 22.5 && CC.lookX === 7.4 && CC.lookY === 4.8,
   'camera pull-back pose');
{
  const halfH = CC.z * Math.tan(CC.fov / 2 * DEG);
  ok(PL.height / (2 * halfH) < 0.09, 'player under 9 percent of screen height');
  const frac = CONFIG.scrollSpeed / (2 * halfH * 16 / 9);
  ok(frac > 0.10 && frac < 0.125, 'scroll crosses ~10-12 percent of screen width per second, got ' + frac);
}
ok(CONFIG.fog.near === 30 && CONFIG.fog.far === 74, 'fog pushed out with the camera');
ok(CONFIG.rifle.radius === 0.16, 'tracer readability radius');
ok(CONFIG.wasp.visualRadius === 0.5 && CONFIG.wasp.contactRadius === 0.55 &&
   CONFIG.wasp.visualRadius < CONFIG.wasp.contactRadius,
   'wasp visual bump stays inside its hitbox');

// --- pattern-chunk generator ------------------------------------------
const LVL = buildLevel(CONFIG);
const gH = LVL.groundH, plats = LVL.platforms;
ok(gH.length === CONFIG.levelLength, 'groundH spans the level');
{
  let bad = 0;
  for (let i = 0; i < gH.length; i++) {
    const g = gH[i];
    if (typeof g !== 'number') { bad++; continue; }
    if (g > -100 && (g < GG.minH || g > GG.maxH)) bad++;
  }
  ok(bad === 0, 'every column defined; solid heights within [minH, maxH]');
}
{
  let flat = true;
  for (let i = 0; i < PP.introTiles; i++) if (gH[i] !== 3) flat = false;
  for (let i = CONFIG.levelLength - GG.tailFlat; i < CONFIG.levelLength; i++) if (gH[i] !== 3) flat = false;
  ok(flat, 'intro and outro tail flat at h=3');
}
{
  let bad = 0;
  for (let i = 1; i < gH.length; i++)
    if (gH[i] > -100 && gH[i - 1] > -100 && Math.abs(gH[i] - gH[i - 1]) > 2) bad++;
  ok(bad === 0, 'adjacent solid steps <= 2');
}
{
  let badRun = 0, badLand = 0, badDelta = 0, gapCols = 0;
  let i = 0;
  while (i < gH.length) {
    if (gH[i] > -100) { i++; continue; }
    const start = i;
    while (i < gH.length && gH[i] < -100) i++;
    const run = i - start;
    gapCols += run;
    if (run > GG.gapMax) badRun++;
    if (start === 0 || i >= gH.length) { badLand++; continue; }
    let solid = 0;
    while (i + solid < gH.length && gH[i + solid] > -100) solid++;
    if (solid < GG.landingMin) badLand++;
    if (Math.abs(gH[start - 1] - gH[i]) > 1) badDelta++;
  }
  ok(badRun === 0, 'gap runs <= gapMax');
  ok(badLand === 0, 'every gap has >= landingMin solid columns after it');
  ok(badDelta === 0, 'height change across each gap <= 1');
  ok(gapCols >= 10, 'terrain actually has gaps, got ' + gapCols + ' gap columns');
}

/* --- FAIR-GAP INVARIANT: every gap crosses at the SCROLL FLOOR ---------- *
 * T-020's triage of I-021. Every full-run measurement this sprint spent its
 * first life at t≈3.0 s at x = 31.649 — the far lip of the first gap (columns
 * 29–31), on pristine `main` and on every branch, to three decimals. It is a
 * geometric constant, not a tuning artifact: 31.649 = 32 − hw − 0.001 is the
 * x-collision resolution against the far lip's wall face, i.e. RIG walked off
 * the near lip and slid down the far one. See
 * docs/playtests/2026-08-first-gap-triage.md.
 *
 * The two guards that were already here are the reason it shipped unseen:
 * `gap runs <= gapMax`, immediately above, asserts a WIDTH, and the
 * frozen-tune check further up ("full jump at run speed clears the widest gap
 * with margin") asserts reach at PL.runSpeed — the fastest RIG can ever move.
 * Neither asks the question a player asks: can I get across from where I am
 * standing, at the speed I actually have? Same failure mode as T-009's, whose
 * pocket assertions were all true and all missed the actual defect because
 * they asserted what the generator intended rather than what a player can do.
 *
 * RIG's ground speed has a floor and a ceiling. The ceiling is runSpeed (9.4).
 * The floor is CONFIG.scrollSpeed (4.3): the right screen clamp in
 * sim/player.js pins x + hw to sRightEdge() − edges.margin, and that edge
 * advances with scrollX, so a player jammed against it crosses ground at
 * exactly the scroll speed however hard they hold right. Every gap must be
 * jumpable at the FLOOR, because a player who has been caught by the plane
 * has no faster option and no way to earn one.
 *
 * The probe below drives the real, unmodified sim/player.js loop over the
 * real generated columns in a CHILD process (like the ?g1=1 equivalence test
 * further down) so it cannot perturb this file's shared clock, keys, edges or
 * weapon state. For every gap it sweeps takeoff positions along the left lip,
 * holds right, presses jump once, and asks whether RIG ends up standing,
 * alive, past the gap — landing on a catwalk that reaches past it counts,
 * because a player standing on one has crossed.
 *
 * T-026 added the probe's own honesty instruments, after I-024 showed the
 * first ones were too weak. The word "floor" in every number below is a claim
 * about a SPEED, and until now it was only defended by comparing takeoff
 * WINDOWS (floor narrower than run) — which a probe that keeps the
 * scroll-speed start but loses the screen clamp passes while measuring an
 * almost-free run. So the probe now meters the mean ground speed of every
 * attempt it makes, and runs one clamp-removed control sweep whose numbers
 * have to come out wrong. Removing the clamp from either sweep function turns
 * the suite red; `node tools/gatecheck.mjs` mutates this file and proves it.  */
{
  // the same gap enumeration the child runs, over this file's own copy of the
  // generated columns — so a probe that silently saw different terrain trips
  const gapRuns = (cols) => {
    const out = [];
    let i = 0;
    while (i < cols.length) {
      if (cols[i] > -100) { i++; continue; }
      const s = i;
      while (i < cols.length && cols[i] < -100) i++;
      if (s > 0 && i < cols.length) out.push([s, i - 1]);
    }
    return out;
  };
  const simURL = 'file://' + join(srcDir, 'sim');
  const gapProbeChild = `
    globalThis.__HB_QUERY__ = '';
    const [T, E, LV, PLm, IN, WG, CF] = await Promise.all([
      import(${JSON.stringify(simURL + '/time.js')}),
      import(${JSON.stringify(simURL + '/edges.js')}),
      import(${JSON.stringify(simURL + '/level.js')}),
      import(${JSON.stringify(simURL + '/player.js')}),
      import(${JSON.stringify(simURL + '/input.js')}),
      import(${JSON.stringify(simURL + '/wavegate.js')}),
      import(${JSON.stringify('file://' + join(srcDir, 'config.js'))}),
    ]);
    const C = CF.CONFIG, PL = C.player, hw = PL.width / 2, M = C.edges.margin;
    const p = PLm.player;
    // No corner may clamp the right edge during the probe: this measures
    // terrain, not the wave-gate pivot wall.
    for (const c of WG.cornerEvents) c.state = 'done';

    const gaps = [];
    { let i = 0;
      while (i < LV.groundH.length) {
        if (LV.groundH[i] > -100) { i++; continue; }
        const s = i;
        while (i < LV.groundH.length && LV.groundH[i] < -100) i++;
        if (s > 0 && i < LV.groundH.length)
          gaps.push({ x0: s, x1: i - 1, w: i - s, hL: LV.groundH[s - 1], hR: LV.groundH[i] });
      } }

    // Every attempt runs in one of three modes. \`speed\` sets the takeoff
    // velocity and whether the scroll plane advances; \`clamp\` sets whether the
    // right screen edge is pinned to RIG. FLOOR is the shipped measurement —
    // plane advancing AND clamp holding, which is what makes ground speed
    // exactly CONFIG.scrollSpeed. CTRL is the honesty control I-024 asked for:
    // the same scroll-speed start with the clamp gone.
    const FLOOR = { id: 'floor', speed: 'floor', clamp: true };
    const RUN   = { id: 'run',   speed: 'run',   clamp: false };
    const CTRL  = { id: 'ctrl',  speed: 'floor', clamp: false };

    // The speed meter: the fastest GROUND SPEED (tiles/second, averaged from an
    // attempt's own first frame) seen since the last reset. THIS is what the
    // "SCROLL speed" label claims, and two nearby quantities are deliberately
    // not the observable:
    //
    //   vx — the right clamp in sim/player.js pins x without touching vx, so a
    //        correctly pinned RIG still accelerates to runSpeed on paper while
    //        covering ground at exactly scrollSpeed;
    //   the per-frame advance — an attempt whose takeoff x sits several tiles
    //        behind the lip starts inside a step, is ejected by the collision
    //        resolver, drops BEHIND the plane, and then legitimately accelerates
    //        to runSpeed catching up to it. Measured: instantaneous 9.4 on a
    //        properly clamped floor sweep, which would make the guard below
    //        unassertable noise.
    //
    // The average from the attempt's start has neither problem: RIG begins the
    // attempt exactly at the plane, and the clamp means he can never be ahead
    // of it, so his mean speed over any prefix of a clamped attempt is
    // scrollSpeed or less however much he lags and catches up inside it.
    const SPEED = {
      max: -Infinity, freeMax: -Infinity, traversalVx: 0,
      frames: 0, traversalFrames: 0,
    };
    let meterX0 = 0, meterFrames = 0, meterTraversalSeen = false;
    function speedReset() {
      SPEED.max = -Infinity;
      SPEED.freeMax = -Infinity;
      SPEED.traversalVx = 0;
      SPEED.frames = 0;
      SPEED.traversalFrames = 0;
    }
    function meterReset() {
      meterX0 = p.x;
      meterFrames = 0;
      meterTraversalSeen = false;
    }
    function meter(dt, traversalBefore) {
      meterFrames++;
      const avg = (p.x - meterX0) / (meterFrames * dt);
      if (avg > SPEED.max) SPEED.max = avg;
      const contextual = traversalBefore !== 'free' || p.traversalState !== 'free' ||
        p.traversalControlUntil > T.gameMs;
      if (contextual) {
        meterTraversalSeen = true;
        SPEED.traversalFrames++;
        SPEED.traversalVx = Math.max(SPEED.traversalVx, Math.abs(p.vx));
      }
      if (!meterTraversalSeen && avg > SPEED.freeMax) SPEED.freeMax = avg;
      SPEED.frames++;
    }

    // One attempt. RIG stands on the left lip at takeoff x0, holds right,
    // presses jump on frame 0 (again at the apex when air=true), and touches
    // nothing else. mode.clamp pins him against the right screen clamp, so his
    // ground speed is exactly CONFIG.scrollSpeed; RUN lets him run free.
    function cross(g, x0, dt, air, mode) {
      for (const k in IN.keys) IN.keys[k] = false;
      IN.clearJumpBuffer(); PLm.clearPlayerTraversal(0); T.setScrollX(0);
      p.x = x0; p.y = g.hL;
      p.vx = mode.speed === 'floor' ? C.scrollSpeed : PL.runSpeed; p.vy = 0;
      p.grounded = true; p.onOneWay = null;
      p.airJumpsLeft = PL.airJumps; p.coyoteUntil = 0; p.dropUntil = 0;
      p.jumpCutDone = true; p.hp = PL.maxHealth; p.lives = PL.lives;
      p.iframesUntil = 0; p.hitstunUntil = 0; p.traversalControlUntil = 0;
      if (mode.clamp) E.setEdges(x0 + hw + M - 200, x0 + hw + M);
      else E.setEdges(-1000, 1000);
      IN.keys.right = true; IN.keys.jump = true;
      IN.bufferJumpUntil(T.gameMs + PL.jumpBufferMs);
      meterReset();
      let airLeft = air, prevVy = 0;
      for (let i = 0, n = Math.ceil(4 / dt); i < n; i++) {
        if (airLeft && i > 0 && prevVy > 0 && p.vy <= 0) {
          IN.bufferJumpUntil(T.gameMs + PL.jumpBufferMs); airLeft = false;
        }
        prevVy = p.vy;
        T.advanceGameMs(dt * 1000);
        if (mode.speed === 'floor') T.setScrollX(T.scrollX + C.scrollSpeed * dt);
        const traversalBefore = p.traversalState;
        PLm.updatePlayer(dt);
        meter(dt, traversalBefore);
        // Bail before the kill plane so the probe never runs the death path
        // (loseLife would touch weapons, mods and the score). Gap height
        // deltas are capped at 1 tile, so 2 below the takeoff lip is a fall.
        if (p.y < g.hL - 2) return false;
        if (p.grounded && i > 2 && p.x - hw > g.x1 + 0.5) return true;
      }
      return false;
    }

    // The takeoff window: the run of positions on the left lip from which that
    // one press crosses. hi is the last x where RIG is still grounded — the
    // sim's own rule, floor(x - hw + 0.02) still indexing the lip column.
    function windowFor(g, dt, air, mode) {
      const hi = g.x0 + hw - 0.02;
      let lo = null, up = null;
      for (let n = 0; ; n++) {
        const x = g.x0 - 8 + n * 0.02;
        if (x > hi) break;
        if (cross(g, x, dt, air, mode)) { if (lo === null) lo = x; up = x; }
      }
      return { lo, up, width: lo === null ? 0 : up - lo, atLip: cross(g, hi, dt, air, mode) };
    }

    // Late-press grace: run off the lip at full speed and press jump n frames
    // LATE. Measured twice. With air=false the air jump is withheld, which
    // isolates coyote time — and on a level gap that buys ZERO frames: one
    // frame past the lip RIG's feet are already below the far lip's top, and a
    // jump only restores the height it left from, so he arrives at the far
    // wall's FACE instead of its top. With air=true (the real game) the late
    // press spends the air jump instead, and that is what actually forgives it.
    function graceFrames(g, dt, mode, air) {
      const hi = g.x0 + hw - 0.02;
      let n = 0;
      for (; n < 40; n++) {
        for (const k in IN.keys) IN.keys[k] = false;
        IN.clearJumpBuffer(); PLm.clearPlayerTraversal(0); T.setScrollX(0);
        p.x = hi; p.y = g.hL;
        p.vx = mode.speed === 'floor' ? C.scrollSpeed : PL.runSpeed; p.vy = 0;
        p.grounded = true; p.onOneWay = null; p.coyoteUntil = 0; p.dropUntil = 0;
        p.jumpCutDone = true; p.hp = PL.maxHealth; p.lives = PL.lives;
        p.iframesUntil = 0; p.hitstunUntil = 0; p.traversalControlUntil = 0;
        if (mode.clamp) E.setEdges(hi + hw + M - 200, hi + hw + M); else E.setEdges(-1000, 1000);
        IN.keys.right = true;
        meterReset();
        let crossed = false, pressed = false;
        for (let i = 0, fr = Math.ceil(4 / dt); i < fr; i++) {
          p.airJumpsLeft = air ? PL.airJumps : 0;
          if (i === n) { IN.keys.jump = true; IN.bufferJumpUntil(T.gameMs + PL.jumpBufferMs); pressed = true; }
          T.advanceGameMs(dt * 1000);
          if (mode.speed === 'floor') T.setScrollX(T.scrollX + C.scrollSpeed * dt);
          const traversalBefore = p.traversalState;
          PLm.updatePlayer(dt);
          meter(dt, traversalBefore);
          if (p.y < g.hL - 2) break;
          if (p.grounded && pressed && i > n + 2 && p.x - hw > g.x1 + 0.5) { crossed = true; break; }
        }
        if (!crossed) break;
      }
      return n - 1;
    }

    const dt = 1 / 60;
    const out = gaps.map((g, gi) => {
      // Everything labelled "floor" is measured with the meter running, and the
      // max it saw is reported beside the windows it produced. A floor column
      // measured at any speed above CONFIG.scrollSpeed is mislabelled, however
      // plausible its windows look.
      speedReset();
      const single = windowFor(g, dt, false, FLOOR);
      const dbl = single.lo === null ? windowFor(g, dt, true, FLOOR) : single;
      const floorGrace = graceFrames(g, dt, FLOOR, true);
      const floorGraceGround = graceFrames(g, dt, FLOOR, false);
      const floorAdvance = +SPEED.max.toFixed(6);
      const floorFrames = SPEED.frames;

      speedReset();
      const run = windowFor(g, dt, false, RUN);
      const runGrace = graceFrames(g, dt, RUN, true);
      const runAdvance = +SPEED.max.toFixed(6);
      const runFreeAdvance = +SPEED.freeMax.toFixed(6);
      const runTraversalVx = +SPEED.traversalVx.toFixed(6);
      const runTraversalFrames = SPEED.traversalFrames;

      // The clamp-removed control, run on the first gap — the one I-024
      // measured. Same scroll-speed start, screen clamp gone. If this does not
      // read faster than the floor and open a wider takeoff window, then the
      // meter above is stuck and its silence proves nothing.
      let control = null;
      if (gi === 0) {
        speedReset();
        const w = windowFor(g, dt, false, CTRL);
        control = { single: +w.width.toFixed(4), advance: +SPEED.max.toFixed(6), frames: SPEED.frames };
      }

      return { x0: g.x0, x1: g.x1, w: g.w, hL: g.hL, hR: g.hR,
        floorSingle: +single.width.toFixed(4), floorSingleAtLip: single.atLip,
        floorAny: +dbl.width.toFixed(4), needsAirJump: single.lo === null,
        runSingle: +run.width.toFixed(4), runSingleAtLip: run.atLip,
        floorGrace, runGrace, floorGraceGround,
        floorAdvance, floorFrames, runAdvance,
        runFreeAdvance, runTraversalVx, runTraversalFrames, control };
    });
    console.log(JSON.stringify({ gate1: WG.cornerEvents[0].s, gaps: out }));
  `;
  let probe = null;
  try {
    probe = JSON.parse(execFileSync(process.execPath,
      ['--input-type=module', '-e', gapProbeChild],
      { encoding: 'utf8', maxBuffer: 16 * 1024 * 1024 }));
  } catch (e) {
    console.error('pathcheck: gap-crossing probe child failed: ' + e.message);
  }
  ok(!!probe, 'the gap-crossing probe drives the real player loop headlessly');
  if (probe) {
    const G = probe.gaps;
    ok(G.length === gapRuns(gH).length && G.length >= 8,
       'the probe saw every generated gap (' + G.length + ')');
    // A fair gap is one whose takeoff window is at least as wide as the game's
    // own forgiveness: CONFIG.player.jumpBufferMs of travel at the floor speed.
    // Narrower than that and the input buffer cannot cover a mistimed press.
    const MIN_W = PL.jumpBufferMs / 1000 * CONFIG.scrollSpeed;
    const face1 = G.filter((g) => g.x1 < probe.gate1);
    ok(face1.length >= 2, 'face 1 has gaps to check before the first wave gate (' +
       face1.length + ' before s=' + probe.gate1 + ')');
    const fmt = (g) => g.x0 + '-' + g.x1 + '(w' + g.w + ') floor ' + g.floorSingle.toFixed(2) +
      't/' + (g.floorSingle / CONFIG.scrollSpeed * 1000).toFixed(0) + 'ms';
    {
      const thin = face1.filter((g) => g.floorSingle < MIN_W || !g.floorSingleAtLip);
      ok(thin.length === 0,
         'every face-1 gap before the first wave gate is crossable from the deck at SCROLL speed ' +
         'with one held jump, window >= one jump buffer (' + MIN_W.toFixed(2) + ' tiles): ' +
         face1.map(fmt).join(', ') + (thin.length ? ' -- FAILS: ' + thin.map(fmt).join(', ') : ''));
    }
    {
      const worst = Math.min.apply(null, face1.map((g) => g.runSingle));
      // Strictly wider, not merely wider-or-equal: at 2.2x the ground speed the
      // same gap must be easier. Equality would mean the right-clamp pin never
      // bit and the "floor" column was quietly measured at run speed.
      ok(face1.every((g) => g.runSingle > g.floorSingle && g.runSingleAtLip),
         'the same gaps are wider still at run speed, worst window ' + worst.toFixed(2) +
         ' tiles (the probe really is measuring the floor, not a free run)');
    }
    {
      /* I-024: the window comparison above is NOT enough on its own.
       * It catches a probe started at runSpeed — the builder's own negative
       * control — but not one that keeps the scroll-speed start and loses the
       * screen clamp. Measured, that case lets RIG accelerate to runSpeed in
       * the air: the gap-29-31 "floor" window balloons 0.74 -> 4.12 tiles,
       * still strictly under the 4.22 run-speed window, so the comparison stays
       * green while the column labelled SCROLL reports an almost-free run.
       *
       * Measured on this tree while wiring the control up: a full clamp removal
       * DOES also trip the comparison above — but only because face 1's other
       * gap, 46-47, saturates (floor window 1.96 -> 8.32, exactly its own run
       * window), not because of any property of the check. On the gap I-024
       * named it stays green. A guard that catches a defect only when some
       * unrelated second gap happens to saturate is not a guard.
       *
       * The label is a claim about a SPEED, so assert the speed. The three
       * checks below are one unit: the floor column really ran at the floor,
       * the meter that says so is not stuck, and the clamp is what holds it.
       *
       * Also measured, and worth knowing before editing the probe: forcing the
       * floor sweep's takeoff velocity to runSpeed while the clamp still holds
       * changes NOTHING — all 17 gaps report identical windows, graces and mean
       * speeds. The clamp is what makes the floor a floor; the start velocity
       * only matters once the clamp is gone. */
      const EPS = 1e-6;
      const SS = CONFIG.scrollSpeed;
      const fastest = Math.max.apply(null, G.map((g) => g.floorAdvance));
      const fast = G.filter((g) => g.floorAdvance > SS + EPS);
      ok(fast.length === 0,
         'every floor-labelled sweep really ran at the scroll floor: fastest mean ground speed ' +
         fastest.toFixed(4) + ' vs CONFIG.scrollSpeed ' + SS + ' tiles/s, over ' +
         G.reduce((n, g) => n + g.floorFrames, 0) + ' measured frames' +
         (fast.length ? ' -- FAILS at ' + fast.map((g) => g.x0 + '-' + g.x1 + ' (' +
            g.floorAdvance.toFixed(3) + ')').join(', ') : ''));
      // Non-vacuity, half one: ordinary, unassisted approach frames still read
      // runSpeed. Normal-run ledge/wall contacts are intentional verbs; their
      // mantle snap is contextual displacement, not ground acceleration, and
      // their handoff velocity has its own configured bound below.
      const slowRun = G.filter((g) =>
        g.runFreeAdvance < SS + 1 || g.runFreeAdvance > PL.runSpeed + EPS);
      ok(slowRun.length === 0,
         'the speed meter is live: unassisted run approach reads ' +
         Math.min.apply(null, G.map((g) => g.runFreeAdvance)).toFixed(2) + '-' +
         Math.max.apply(null, G.map((g) => g.runFreeAdvance)).toFixed(2) +
         ' tiles/s, between the floor (' + SS + ') and runSpeed (' + PL.runSpeed + ')' +
         (slowRun.length ? ' -- FAILS at ' + slowRun.map((g) =>
           g.x0 + '-' + g.x1 + ' (' + g.runFreeAdvance.toFixed(3) + ')').join(', ') : ''));
      const contextual = G.filter((g) => g.runAdvance > PL.runSpeed + EPS);
      const traversalBound = Math.max(PL.runSpeed, PL.ledgeLaunchX, PL.wallJumpX);
      ok(contextual.length > 0 && contextual.every((g) =>
           g.runTraversalFrames > 0 && g.runTraversalVx <= traversalBound + EPS),
         'contextual ledge/wall displacement is classified separately: ' +
         contextual.map((g) => g.x0 + '-' + g.x1 + ' mean ' +
           g.runAdvance.toFixed(3) + ', traversal vx ' + g.runTraversalVx.toFixed(3)).join('; ') +
         ' (configured horizontal launch bound ' + traversalBound.toFixed(2) + ')');
      // Non-vacuity, half two: I-024's exact mutation, run for real on the first
      // gap — scroll-speed start kept, screen clamp removed. If the clamp were
      // not what holds the floor, this control would read the floor too and the
      // guard above would be protecting nothing.
      const c = G[0].control;
      ok(!!c && c.advance > SS + 1 && c.single > G[0].floorSingle,
         'negative control (scroll-speed start, screen clamp removed) on gap ' +
         G[0].x0 + '-' + G[0].x1 + ': mean ground speed ' + (c ? c.advance.toFixed(2) : 'n/a') +
         ' tiles/s and a ' + (c ? c.single.toFixed(2) : 'n/a') + '-tile takeoff window against the ' +
         'clamped floor\'s ' + G[0].floorSingle.toFixed(2) + ' -- and note it stays under the ' +
         G[0].runSingle.toFixed(2) + '-tile run-speed window, which is exactly why the ' +
         'window comparison alone could not see it');
    }
    {
      // The first gap the run presents, named: it is the first thing the game
      // teaches, and I-021 says it is where every measured run died.
      const first = G[0];
      ok(first.x0 === 29 && first.x1 === 31 && first.w === 3 && first.hL === 2 && first.hR === 2,
         'the first gap is still columns 29-31 at h=2 (' + fmt(first) + ')');
      ok(first.floorSingle >= MIN_W && first.floorSingleAtLip && first.runSingle >= 4,
         'the first gap is jumpable both ways: ' + first.floorSingle.toFixed(2) +
         ' tiles of takeoff at the scroll floor, ' + first.runSingle.toFixed(2) + ' at run speed');
    }
    {
      // A late press must still cross. Note the third figure in the message:
      // with the air jump withheld the grace is 0 frames on every level gap —
      // one frame past the lip RIG's feet are below the far lip's top and a
      // jump only restores the height it left from, so coyote time cannot
      // save a flat gap. The air jump is what actually forgives it.
      const coyoteFrames = Math.round(PL.coyoteMs / 1000 * 60);
      const stingy = face1.filter((g) => g.floorGrace < coyoteFrames);
      ok(stingy.length === 0,
         'a press up to ' + coyoteFrames + ' frames late (one coyote window) still crosses every ' +
         'face-1 gap at the scroll floor, measured ' +
         face1.map((g) => g.x0 + '-' + g.x1 + ': ' + g.floorGrace + 'f floor / ' + g.runGrace +
                   'f run / ' + g.floorGraceGround + 'f without the air jump').join(', '));
    }
    {
      const stuck = G.filter((g) => g.floorAny < MIN_W);
      ok(stuck.length === 0,
         'EVERY generated gap is crossable from the deck at the scroll floor with the taught ' +
         'vocabulary (run, jump, air jump)' + (stuck.length ? ' -- FAILS: ' + stuck.map(fmt).join(', ') : ''));
      // Two of the wide gaps clear only because a mid-lane catwalk sits over
      // them and catches RIG mid-flight. That is a real route, but it is
      // incidental — the tier pass does not know where the gaps are, and the
      // reachability prune can delete a catwalk. Kept visible on purpose.
      const air = G.filter((g) => g.needsAirJump);
      ok(air.every((g) => g.x1 >= probe.gate1),
         'no gap needing the air jump at the floor speed appears before the first wave gate' +
         (air.length ? ' (air-jump-only: ' + air.map((g) => g.x0 + '-' + g.x1).join(', ') + ')'
                     : ' (none in the level)'));
    }
  }
}

{
  const kinds = new Set(LVL.chunkLog);
  ok(kinds.size >= 6, 'chunk variety: ' + kinds.size + ' of 8 kinds used');
  ok(gH.includes(GG.minH) && gH.includes(GG.maxH), 'height band fully used (2 and 4 both appear)');
}
{
  let clean = true;
  for (const cs of CORNER_S) {
    for (let s = cs - 5; s <= cs + 2; s++) if (gH[s] !== 3) clean = false;
    for (const p of plats) if (p.x1 >= cs - 3 && p.x0 <= cs + 3) clean = false;
  }
  ok(clean, 'corner aprons flat and platform-free');
}
{
  ok(plats.length >= 20, 'catwalk lanes generated, got ' + plats.length);
  let badProceduralY = 0, badAssaultY = 0, assaultPeak = -Infinity, unreachable = 0;
  const assaultCapY = GG.minH + VERTICAL_ASSAULT.spans.at(-1);
  for (const p of plats) {
    if (p.assault) {
      assaultPeak = Math.max(assaultPeak, p.y);
      if (p.y > assaultCapY) badAssaultY++;
    } else if (p.y > GG.laneCapY) badProceduralY++;
    let best = -999;
    for (let k = Math.max(0, p.x0 - 1); k <= Math.min(gH.length - 1, p.x1 + 1); k++)
      if (gH[k] > -100) best = Math.max(best, gH[k]);
    for (const q of plats)
      if (q !== p && q.y < p.y && q.x1 > p.x0 - 1 && q.x0 < p.x1 + 1) best = Math.max(best, q.y);
    if (p.y - best > GG.maxReach) { unreachable++; console.error('  unreachable catwalk ' + JSON.stringify(p)); }
  }
  ok(badProceduralY === 0,
     'procedural catwalks remain capped at laneCapY');
  ok(badAssaultY === 0 && assaultPeak === 17 && assaultCapY === 17,
     'authored Vertical Assault alone may exceed laneCapY, with its final apex pinned at 17');
  ok(unreachable === 0, 'every catwalk within double-jump reach');
}

// --- authored traversal slice ------------------------------------------
// Re-pinned for Vertical Assault v2: each face now owns a distinct authored
// split/rejoin silhouette and anonymous procedural catwalk carpet is removed
// from its play strip. The same six pockets, public arena/arrival IDs, safe
// seed bridges and 59-chunk deck remain; 73 intentional surfaces replace the
// old 87-bar composition. The chunk stream is untouched (same seed/rng draws).
ok(gH.length === 445 && plats.length === 73 && LVL.chunkLog.length === 59,
   'normal generator shape pinned (445 columns / 73 platforms / 59 chunks), got ' +
   gH.length + '/' + plats.length + '/' + LVL.chunkLog.length);
// Moved three times inside T-009 and then moved BACK. Two passes lifted the
// capsule out of the deck-line jump arc (rewardRise 0.7 -> 1.75, then a shelf
// tier of the pocket's own at +4.45) because collecting it was supposed to
// cost a retreat; decisions.md entry 9 withdrew that requirement, so the
// pocket is the plain shape again — shelf one generator tier over its mid
// lane, capsule +0.7 over the tip. The chunk stream never moved at all (same
// 445 columns, same 59 chunks, same rng draws — the lattice consumes none);
// what moves with the shelf height is the bands the patch pass reads, and at
// the plain shape that is one catwalk fewer than the raised tier produced.
// Re-pinned with the six face-specific support families. Geometry and the
// fixed rewards are unchanged; the fingerprint now also covers the authored
// rib/service/cavity/vent/braid/root presentation metadata consumed by the
// production dressing pass.
ok(fingerprint(LVL) === '7428339f',
   'normal generator fingerprint unchanged, got ' + fingerprint(LVL));

const fixtureBefore = JSON.stringify(TRAVERSAL_FIXTURE);
const configBefore = JSON.stringify(CONFIG);
const TL = buildTraversalLevel(CONFIG);
const TL2 = buildTraversalLevel(CONFIG);
ok(JSON.stringify(TL) === JSON.stringify(TL2),
   'traversal fixture builds deterministically');
ok(JSON.stringify(TRAVERSAL_FIXTURE) === fixtureBefore && JSON.stringify(CONFIG) === configBefore,
   'traversal build does not mutate fixture metadata or CONFIG');
ok(TL !== TL2 && TL.groundH !== TL2.groundH && TL.platforms !== TL2.platforms &&
   TL.solidRects !== TL2.solidRects &&
   TL.solidRects.every(function (r, i) { return r !== TL2.solidRects[i]; }),
   'traversal builds return fresh geometry arrays and solid objects');

const TF = TRAVERSAL_FIXTURE;
const TP = { ...PL, ...TF.movement };
const B = TF.bounds;
ok(Number.isInteger(B.x0) && Number.isInteger(B.x1) &&
   B.x0 >= 0 && B.x0 < B.x1 && B.x1 <= CONFIG.levelLength,
   'fixture bounds are a valid half-open level interval');
ok(TL.groundH.length === CONFIG.levelLength &&
   TL.groundH.every(function (h) { return Number.isFinite(h); }),
   'traversal ground spans the level with finite numeric heights');

{
  let valid = true;
  const covered = new Set();
  for (const run of TF.groundRuns) {
    if (!Number.isInteger(run.x0) || !Number.isInteger(run.x1) ||
        !Number.isFinite(run.y) || run.x0 < B.x0 || run.x1 > B.x1 ||
        run.x0 >= run.x1) valid = false;
    for (let x = run.x0; x < run.x1; x++) {
      if (covered.has(x) || TL.groundH[x] !== run.y) valid = false;
      covered.add(x);
    }
  }
  ok(valid && covered.size === B.x1 - B.x0,
     'authored ground runs cover fixture bounds once and match built heights');
}
{
  const ids = new Set();
  let valid = true;
  for (const p of TF.platforms) {
    if (typeof p.id !== 'string' || ids.has(p.id) ||
        !Number.isFinite(p.x0) || !Number.isFinite(p.x1) || !Number.isFinite(p.y) ||
        p.x0 < B.x0 || p.x1 > B.x1 || p.x0 >= p.x1) valid = false;
    ids.add(p.id);
  }
  ok(valid && ids.size === TF.platforms.length,
     'authored platforms have unique ids and finite in-bounds spans');
}
{
  const ids = new Set();
  let valid = true, halfOpen = true, built = true;
  for (const r of TF.solidRects) {
    if (typeof r.id !== 'string' || ids.has(r.id) ||
        ![r.x0, r.x1, r.y0, r.y1].every(Number.isInteger) ||
        r.x0 < B.x0 || r.x1 > B.x1 || r.x0 >= r.x1 || r.y0 >= r.y1 ||
        (r.grabbable !== undefined && typeof r.grabbable !== 'boolean')) valid = false;
    ids.add(r.id);
    if (!solidRectContains(r, r.x0, r.y0) ||
        !solidRectContains(r, r.x1 - 1, r.y1 - 1) ||
        solidRectContains(r, r.x1, r.y0) ||
        solidRectContains(r, r.x0, r.y1) ||
        solidRectContains(r, r.x0 - 1, r.y0)) halfOpen = false;
    if (!levelSolidCell(TL, r.x0, r.y0, 8)) built = false;
  }
  ok(valid && ids.size === TF.solidRects.length,
     'authored solid rectangles have unique ids and integer in-bounds extents');
  ok(halfOpen, 'solid rectangle membership is half-open on x and y');
  ok(built, 'level solid predicate includes every authored solid rectangle');
}
{
  const deadEnd = TF.solidRects.find(function (r) { return r.id === 'dare-dead-end'; });
  ok(!!deadEnd &&
     !traversalSolidAllowsGrab(TF, deadEnd.x0, deadEnd.y0, PL.height) &&
     traversalSolidAllowsGrab(TF, 39, 5, PL.height) &&
     traversalSolidAllowsGrab(null, deadEnd.x0, deadEnd.y0, PL.height),
     'dare dead-end rejects hidden wall adhesion without changing other walls or normal mode');
}
{
  const overhangs = TF.solidRects.filter(function (r) { return r.role === 'overhang'; });
  const o = overhangs[0];
  const x = o && Math.floor((o.x0 + o.x1) / 2);
  ok(overhangs.length === 1, 'fixture declares exactly one tagged overhang');
  ok(!!o && levelSolidCell(TL, x, o.y0, 8) &&
     !levelSolidCell(TL, x, o.y0 - 1, 8) &&
     !levelSolidCell(TL, x, o.y1, 8),
     'overhang is solid while its underside and space above stay open');
  ok(!!o && o.y0 - TL.groundH[x] > PL.height + 0.5,
     'overhang leaves player-height clearance below it');
}
{
  const x = B.x0, ground = TL.groundH[x];
  ok(levelSolidCell(TL, x, ground - 1, 8) && !levelSolidCell(TL, x, ground, 8),
     'level solid predicate preserves half-open ground-top collision');
}

const connectorById = new Map();
let connectorIntegrity = true;
for (const c of TF.connectors) {
  if (typeof c.id !== 'string' || connectorById.has(c.id) ||
      !Number.isFinite(c.x) || !Number.isFinite(c.y) ||
      c.x < B.x0 || c.x >= B.x1 ||
      levelSolidCell(TL, Math.floor(c.x), Math.floor(c.y), 8)) connectorIntegrity = false;
  connectorById.set(c.id, c);
}
ok(connectorIntegrity && connectorById.size === TF.connectors.length &&
   connectorById.has(TF.entry) && connectorById.has(TF.exit),
   'connectors are unique, finite, in bounds, open, and include entry/exit');

const routeById = new Map(TF.routes.map(function (r) { return [r.id, r]; }));
let edgeIntegrity = true;
for (const e of TF.edges) {
  if (!routeById.has(e.routeId) || !connectorById.has(e.from) ||
      !connectorById.has(e.to) || e.from === e.to ||
      typeof e.verb !== 'string' || e.verb.length === 0) edgeIntegrity = false;
}
ok(edgeIntegrity, 'every traversal edge names a route, two connectors, and a verb');
ok(TF.routes.length === 6 && routeById.size === 6,
   'fixture declares six uniquely named traversal routes');

{
  let valid = true;
  const used = new Set();
  for (const route of TF.routes) {
    const ids = route.connectorIds;
    if (!Array.isArray(ids) || ids.length < 2 ||
        ids[0] !== TF.entry || ids[ids.length - 1] !== TF.exit) valid = false;
    for (let i = 1; i < ids.length; i++) {
      const found = TF.edges.some(function (e) {
        return e.routeId === route.id && e.from === ids[i - 1] && e.to === ids[i];
      });
      if (!found) valid = false;
      used.add(route.id + '|' + ids[i - 1] + '|' + ids[i]);
    }
  }
  const allUsed = TF.edges.every(function (e) {
    return used.has(e.routeId + '|' + e.from + '|' + e.to);
  });
  ok(valid, 'all six route sequences travel entry to rejoin on consecutive declared edges');
  ok(allUsed, 'every declared traversal edge participates in its route sequence');
}
{
  const outgoing = new Map(), incoming = new Map();
  for (const e of TF.edges) {
    if (!outgoing.has(e.from)) outgoing.set(e.from, new Set());
    if (!incoming.has(e.to)) incoming.set(e.to, new Set());
    outgoing.get(e.from).add(e.to);
    incoming.get(e.to).add(e.from);
  }
  let maxChoices = 0;
  for (const choices of outgoing.values()) maxChoices = Math.max(maxChoices, choices.size);
  const fork = TF.firstFork;
  ok(maxChoices >= 2 && maxChoices <= TF.immediateChoiceCap &&
     TF.immediateChoiceCap === 3,
     'graph splits without exceeding the three-choice readability cap');
  ok(fork.connector === TF.entry && fork.choices.length >= 2 &&
     fork.choices.length <= TF.immediateChoiceCap &&
     fork.choices.every(function (id) { return connectorById.has(id); }),
     'declared first fork offers valid bounded route choices');
  ok((incoming.get(TF.exit) || new Set()).size >= 2 &&
     TF.routes.every(function (r) { return r.connectorIds[r.connectorIds.length - 1] === TF.exit; }),
     'alternate routes reconnect through a shared exit');
  const elevations = new Set(TF.connectors.map(function (c) {
    return Math.round(c.y * 100) / 100;
  }));
  ok(elevations.size >= 5, 'connector graph uses at least five distinct elevations');
}
{
  const verbs = new Set(TF.edges.map(function (e) { return e.verb; }));
  ok(Array.from(verbs).some(function (v) { return v.indexOf('ledge') >= 0 || v.indexOf('catch') >= 0; }) &&
     Array.from(verbs).some(function (v) { return v.indexOf('wall') >= 0; }),
     'route graph exercises both ledge-catch and wall-jump verbs');
}

{
  const D = TF.darePocket;
  const dareRoute = routeById.get('dare-pocket');
  const rewardRoutes = TF.routes.filter(function (r) {
    return r.connectorIds.indexOf(D.rewardConnector) >= 0;
  });
  ok(!!dareRoute && rewardRoutes.length === 1 && rewardRoutes[0].id === dareRoute.id &&
     TF.routes.some(function (r) { return r.connectorIds.indexOf(D.rewardConnector) < 0; }),
     'dare reward is optional and confined to its named route');
  let retreatValid = D.retreatPath[0] === D.rewardConnector &&
    D.retreatPath[D.retreatPath.length - 1] === D.rejoin;
  for (let i = 1; i < D.retreatPath.length; i++) {
    if (!TF.edges.some(function (e) {
      return e.routeId === dareRoute.id &&
        e.from === D.retreatPath[i - 1] && e.to === D.retreatPath[i];
    })) retreatValid = false;
  }
  ok(retreatValid, 'dare reward has a directed retreat path back to the declared rejoin');

  const nominalSeconds = (TF.rejoin.x0 - TF.run.playerSpawn.x) / TP.runSpeed;
  ok(Number.isFinite(nominalSeconds) &&
     nominalSeconds >= TF.targetPlaySeconds.min &&
     nominalSeconds <= TF.targetPlaySeconds.max,
     'slice uninterrupted sprint stays in the fast target range, got ' + nominalSeconds.toFixed(2) + ' s');
  const retreatAdvance = D.timing.retreatSeconds * TF.run.minimumScrollSpeed;
  const retreatDistance = D.reward.x - D.bounds.x0;
  ok(TF.run.minimumScrollSpeed > 0 &&
     TF.run.minimumScrollSpeed < TP.runSpeed &&
     D.timing.entryEdgeMarginTiles - retreatDistance - retreatAdvance + 1e-9 >=
       D.timing.minExitMarginTiles &&
     D.timing.minExitMarginTiles > PL.width + 2 * CONFIG.edges.margin,
     'dare entry margin covers backtrack plus scroll advance and preserves the exit margin');
}
{
  const run = TF.run;
  const playerRight0 = run.playerSpawn.x + PL.width / 2;
  const followStart = run.startScroll + run.followLeadTiles;
  const slack = followStart - playerRight0;
  const timeToFollow = slack / (TP.runSpeed - run.minimumScrollSpeed);
  const nearestForkX = Math.min.apply(null, TF.firstFork.choices.map(function (id) {
    return connectorById.get(id).x;
  }));
  ok(Number.isFinite(timeToFollow) && timeToFollow >= 0.5,
     'opening sprint stays unpinned for at least half a second, got ' + timeToFollow.toFixed(2) + ' s');
  ok(followStart >= nearestForkX + PL.width / 2,
     'camera-follow threshold reaches the first authored route choice');
  ok(traversalFollowTarget(run.startScroll, playerRight0, 100, run) === run.startScroll &&
     traversalFollowTarget(run.startScroll, followStart + 2, 100, run) === run.startScroll + 2 &&
     traversalFollowTarget(run.startScroll, followStart + 2, 10, run) === followStart - 8,
     'camera follow is idle inside its lead and tracks beyond authored or narrow-screen leads');
  ok(TP.wallJumpX * 0.05 < run.lookAheadTiles,
     'camera look-ahead exceeds the largest one-frame contextual launch');
  const portraitAspect = 390 / 844;
  const portraitDepth = traversalCameraDepth(CC.z, portraitAspect, run);
  const portraitWidth = 2 * portraitDepth * Math.tan(CC.fov / 2 * DEG) * portraitAspect;
  ok(traversalCameraDepth(CC.z, 16 / 9, run) === CC.z &&
     portraitDepth > CC.z &&
     portraitDepth <= CC.z * 2 &&
     portraitWidth >= TF.darePocket.timing.entryEdgeMarginTiles + run.lookAheadTiles,
     'portrait pullback preserves retreat room and preview without shrinking play below half scale');
}

  Object.assign(SHARED, { B, CC, GG, LVL, PL, SP, TF, TL, TP, connectorById, gH, routeById, total });   // read by later domains
}
