#!/usr/bin/env node
// GENERATED BY tools/pathcheck-split.mjs
//
// pathcheck.mjs — HULLBREAKER's headless gate. Run from the repo root:
//
//   node tools/pathcheck.mjs
//
// The assertions live in tools/pathcheck/ — one module per domain, walked in the
// order tools/pathcheck/manifest.mjs lists. This file is a runner and nothing else,
// so two lanes adding assertions touch two different files and never conflict
// (T-037; before it, every task appended to one 9,230-line file and the
// T-025/T-027 merge dropped assertions twice while still printing green).
//
// The layer guards and the ok()/near() helpers live in tools/pathcheck/_context.mjs,
// which is evaluated before any domain, exactly where it sat in the monolith.

import { counts } from './pathcheck/_context.mjs';
import { DOMAINS } from './pathcheck/manifest.mjs';

const SHARED = {};                 // values that travel between domains
for (const domain of DOMAINS) await domain.run(SHARED);

// The tally and exit below are the monolith's own two final statements, moved
// here verbatim: the output line and the exit code are a contract that
// tools/orch/merge-task.sh, tools/gatecheck.mjs and every gate agent read.
const { passes, fails } = counts();
console.log('pathcheck: ' + passes + ' passed, ' + fails + ' failed');
process.exit(fails ? 1 : 0);
